In [263]:
import pandas as pd
import numpy as np
import re

In [308]:
cols = {'구분' : '총전입'}
values = '총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출'.split(',')
for i in range(1,8):
    cols[f'구분.{i}'] = values[i-1]
cols

{'구분': '총전입',
 '구분.1': '총전출',
 '구분.2': '구내전입',
 '구분.3': '구내전출',
 '구분.4': '구간전입',
 '구분.5': '구간전출',
 '구분.6': '시/도간전입',
 '구분.7': '시/도간전출'}

In [330]:
def cleaning_df(year):
    df = pd.read_csv(f'data/data_org/seoul_in_out_{year}_org.csv')
    df = df.drop(0).drop(1)
    print(year)
    print(df.shape)
    print(df.columns)
    df = df.rename(columns=cols)
#     정리된거 저장도 같이 해두자
    df = df.apply(lambda x: x.str.replace(',', ''))
    print(df.iloc[:3,:])
    df.to_csv(f'data/seoul_in_out_{year}.csv', index=False)
    
    return df

In [331]:
def concat_dfs(year, result):
    df = cleaning_df(year)
    result = result.append(df, ignore_index=True)
    return result

In [332]:
result = pd.DataFrame(columns=['기간', '자치구', '동', '총전입', '총전출', '구내전입',\
                               '구내전출', '구간전입', '구간전출','시/도간전입', '시/도간전출'])
result.head()

Empty DataFrame
Columns: [기간, 자치구, 동, 총전입, 총전출, 구내전입, 구내전출, 구간전입, 구간전출, 시/도간전입, 시/도간전출]
Index: []

In [333]:
for year in range(2009, 2018):
    result = concat_dfs(year, result)
result.shape

2009
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2009   합계   합계  1873188  1925452  560864  560864  725991  725991  586333
3  2009  종로구   소계    31031    33661    5921    5921   15157   18036    9953
4  2009  종로구  사직동     2140     2076     448     402    1087    1160     605

   시/도간전출
2  638597
3    9704
4     514
2010
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2010   합계   합계  1733015  1848038  520345  520345  679363  679363  533307
3  2010  종로구   소계    29208    32928    5703    5703   14256   17822    9249
4  2010  종로구  사직동     2041     2261     433     445    1017    1209     591

   시/도간전출
2  648330
3    9403
4     607
2011
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2011   합계   합계  1721748  1834806  543807  543807  671315  671315  506626
3  2011  종로구   소계    28329    30663    5551    5551   14089   16214    8689
4  2011  종로구  사직동     2115     2215     467     487    1047    1133     601

   시/도간전출
2  619684
3    8898
4     595
2012
(449, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2012   총계   총계  1555281  1658928  473458  473458  595842  595842  485981
3  2012  종로구   소계    26001    29398    4935    4935   12530   15681    8536
4  2012  종로구  사직동     1811     1979     415     417     924     997     472

   시/도간전출
2  589628
3    8782
4     565
2013
(449, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2013   합계   합계  1520090  1620640  468394  468394  584614  584614  467082
3  2013  종로구   소계    24676    30007    4921    4921   11803   16405    7952
4  2013  종로구  사직동     1665     1872     406     360     828     990     431

   시/도간전출
2  567632
3    8681
4     522
2014
(449, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2014   합계   합계  1573594  1661425  495401  495401  602622  602622  475571
3  2014  종로구   소계    24191    27484    4507    4507   11243   14657    8441
4  2014  종로구  사직동     1694     1840     377     360     833    1003     484

   시/도간전출
2  563402
3    8320
4     477
2015
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2015   합계   합계  1589431  1726687  524267  524267  605262  605262  459902
3  2015  종로구   소계    24951    27470    4617    4617   11846   14426    8488
4  2015  종로구  사직동     1708     1840     294     364     967    1030     447

   시/도간전출
2  597158
3    8427
4     446
2016
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2016   합계   합계  1515602  1655859  487722  487722  574193  574193  453687
3  2016  종로구   소계    23604    26386    4145    4145   11135   13913    8324
4  2016  종로구  사직동     1725     1790     290     301     928     988     507

   시/도간전출
2  593944
3    8328
4     501
2017
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2017   합계   합계  1472937  1571423  454536  454536  564271  564271  454130
3  2017  종로구   소계    28020    25814    4512    4512   14610   13178    8898
4  2017  종로구  사직동     1733     1993     315     517     899     993     519

   시/도간전출
2  552616
3    8124
4     483

(4047, 11)

# 여기서부터 돌리기

In [8]:
import pandas as pd
import numpy as np
import re

In [9]:
result = pd.DataFrame(columns=['기간', '자치구', '동', '총전입', '총전출', '구내전입',\
                               '구내전출', '구간전입', '구간전출','시/도간전입', '시/도간전출'])
result.head()

Empty DataFrame
Columns: [기간, 자치구, 동, 총전입, 총전출, 구내전입, 구내전출, 구간전입, 구간전출, 시/도간전입, 시/도간전출]
Index: []

In [10]:
for year in range(2009, 2018):
    df = pd.read_csv(f'data/seoul_in_out_{year}.csv')
    result = result.append(df, ignore_index=True)
result.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597

In [11]:
result.shape

(4047, 11)

In [12]:
result.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597

In [13]:
result.to_csv('seoul_in_out_total_abs.csv', index=False)

In [14]:
diff_values = result.copy(deep=True)
diff_values = diff_values.iloc[:, 3:]
diff_values.head()

       총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  시/도간전출
0  1873188  1925452  560864  560864  725991  725991  586333  638597
1    31031    33661    5921    5921   15157   18036    9953    9704
2     2140     2076     448     402    1087    1160     605     514
3      694      808     137     191     317     402     240     215
4     1925     2180     477     483     945    1100     503     597

In [15]:
new_cols = '총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출'.split(',')
for i in range(len(new_cols)):
    diff_values[new_cols[i]] = diff_values.iloc[:,i*2].values - diff_values.iloc[:,i*2+1].values
diff_values.head()

,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
0,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264
1,31031,33661,5921,5921,15157,18036,9953,9704,-2630,0,-2879,249
2,2140,2076,448,402,1087,1160,605,514,64,46,-73,91
3,694,808,137,191,317,402,240,215,-114,-54,-85,25
4,1925,2180,477,483,945,1100,503,597,-255,-6,-155,-94

In [16]:
diff_values[['기간', '자치구', '동']] = result.iloc[:,:3].copy(deep=True)
diff_values.head()

,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출,기간,자치구,동
0,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264,2009,합계,합계
1,31031,33661,5921,5921,15157,18036,9953,9704,-2630,0,-2879,249,2009,종로구,소계
2,2140,2076,448,402,1087,1160,605,514,64,46,-73,91,2009,종로구,사직동
3,694,808,137,191,317,402,240,215,-114,-54,-85,25,2009,종로구,삼청동
4,1925,2180,477,483,945,1100,503,597,-255,-6,-155,-94,2009,종로구,부암동

In [17]:
diff_values = diff_values[['기간', '자치구', '동', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출',\
                  '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']]
diff_values.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704,-2630,0,-2879,249
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514,64,46,-73,91
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215,-114,-54,-85,25
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597,-255,-6,-155,-94

In [18]:
diff_values.shape

(4047, 15)

In [19]:
diff_values.to_csv('seoul_in_out_total_diffs.csv', index=False)

# 분류별로 확인하기

In [258]:
'''
현핫플 : 연남동, 익선동, 성수동, 샤로수길(봉천동), 망원동, 사직동
기핫플 : 신사동, 삼청동, 명동
비핫플 : 상도동, 목동, 신정동, 상계동, 명일동
'''

'\n현핫플 : 연남동, 익선동, 성수동, 샤로수길(봉천동), 망원동\n기핫플 : 신사동, 삼청동, 명동\n비핫플 : 상도동, 목동, 신정동, 상계동\n'

In [20]:
diff_values[diff_values['동'] == '연남동']

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
230,2009,마포구,연남동,4149,4369,1154,1301,1688,1716,1307,1352,-220,-147,-28,-45
680,2010,마포구,연남동,3878,4344,1088,1298,1645,1701,1145,1345,-466,-210,-56,-200
1130,2011,마포구,연남동,3748,4123,1113,1229,1501,1644,1134,1250,-375,-116,-143,-116
1579,2012,마포구,연남동,3672,3956,1093,1102,1385,1619,1194,1235,-284,-9,-234,-41
2028,2013,마포구,연남동,3516,3617,993,902,1441,1497,1082,1218,-101,91,-56,-136
2477,2014,마포구,연남동,3343,3898,919,1094,1252,1516,1172,1288,-555,-175,-264,-116
2926,2015,마포구,연남동,3284,3999,905,1036,1307,1767,1072,1196,-715,-131,-460,-124
3376,2016,마포구,연남동,3173,3809,829,922,1141,1754,1203,1133,-636,-93,-613,70
3826,2017,마포구,연남동,2976,3773,742,922,1078,1619,1156,1232,-797,-180,-541,-76

In [21]:
diff_values[diff_values['기간'] == 2012]

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
1350,2012,총계,총계,1555281,1658928,473458,473458,595842,595842,485981,589628,-103647,0,0,-103647
1351,2012,종로구,소계,26001,29398,4935,4935,12530,15681,8536,8782,-3397,0,-3151,-246
1352,2012,종로구,사직동,1811,1979,415,417,924,997,472,565,-168,-2,-73,-93
1353,2012,종로구,삼청동,452,548,92,132,214,280,146,136,-96,-40,-66,10
1354,2012,종로구,부암동,1714,1827,401,352,825,962,488,513,-113,49,-137,-25
1355,2012,종로구,평창동,2535,2685,462,368,1286,1434,787,883,-150,94,-148,-96
1356,2012,종로구,무악동,1206,1254,177,135,761,824,268,295,-48,42,-63,-27
1357,2012,종로구,교남동,1326,2189,208,243,721,1351,397,595,-863,-35,-630,-198
1358,2012,종로구,가회동,780,926,149,207,385,488,246,231,-146,-58,-103,15
1359,2012,종로구,종로1.2.3.4가동,1732,1677,180,231,844,891,708,555,55,-51,-47,153
1360,2012,종로구,종로5·6가동,1038,1055,225,204,447,511,366,340,-17,21,-64,26
1361,2012,종로구,이화동,1632,1877,247,383,699,955,686,539,-245,-136,-256,147
1362,2012,종로구,창신1동,948,1202,279,324,385,571,284,307,-254,-45,-186,-23
1363,2012,종로구,창신2동,1161,1567,339,338,519,799,303,430,-406,1,-280,-127
1364,2012,종로구,창신3동,1022,1229,287,258,534,640,201,331,-207,29,-106,-130
1365,2012,종로구,숭인1동,1162,1367,323,250,527,739,312,378,-205,73,-212,-66
1366,2012,종로구,숭인2동,1633,1708,211,178,936,984,486,546,-75,33,-48,-60
1367,2012,종로구,청운효자동,2248,2444,507,523,1051,1145,690,776,-196,-16,-94,-86
1368,2012,종로구,혜화동,3601,3864,433,392,1472,2110,1696,1362,-263,41,-638,334
1369,2012,중구,소계,24872,25198,4832,4832,13064,13252,6976,7114,-326,0,-188,-138
1370,2012,중구,소공동,422,380,20,31,256,202,146,147,42,-11,54,-1
1371,2012,중구,회현동,1235,996,85,65,784,616,366,315,239,20,168,51
1372,2012,중구,명동,572,603,36,71,339,308,197,224,-31,-35,31,-27
1373,2012,중구,필동,845,893,115,147,390,428,340,318,-48,-32,-38,22
1374,2012,중구,장충동,1154,1189,199,246,392,496,563,447,-35,-47,-104,116
1375,2012,중구,광희동,1002,1094,183,220,471,525,348,349,-92,-37,-54,-1
1376,2012,중구,을지로동,387,440,27,43,207,225,153,172,-53,-16,-18,-19
1377,2012,중구,신당1동,1279,1616,378,573,517,621,384,422,-337,-195,-104,-38
1378,2012,중구,신당2동,2552,2836,691,782,1124,1265,737,789,-284,-91,-141,-52
1379,2012,중구,신당3동,2845,3066,326,567,1710,1509,809,990,-221,-241,201,-181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1769,2012,송파구,가락1동,1365,10368,534,5795,347,2427,484,2146,-9003,-5261,-2080,-1662
1770,2012,송파구,가락2동,4937,5251,2428,2164,1171,1263,1338,1824,-314,264,-92,-486
1771,2012,송파구,문정1동,3760,3935,1719,1536,903,926,1138,1473,-175,183,-23,-335
1772,2012,송파구,문정2동,1726,1923,507,486,718,745,501,692,-197,21,-27,-191
1773,2012,송파구,장지동,6148,6524,2637,1855,1735,1936,1776,2733,-376,782,-201,-957
1774,2012,송파구,잠실본동,5889,5955,1818,1623,2005,1980,2066,2352,-66,195,25,-286
1775,2012,송파구,잠실4동,4844,5422,1678,1628,1930,1967,1236,1827,-578,50,-37,-591
1776,2012,송파구,잠실6동,2276,2535,901,898,726,839,649,798,-259,3,-113,-149
1777,2012,송파구,잠실7동,1060,1107,306,273,489,519,265,315,-47,33,-30,-50
1778,2012,송파구,잠실2동,6536,6987,1714,1808,3081,2817,1741,2362,-451,-94,264,-621
1779,2012,송파구,잠실3동,5409,5845,1991,1860,2107,2063,1311,1922,-436,131,44,-611
1780,2012,강동구,소계,73218,82966,32096,32096,20554,22036,20568,28834,-9748,0,-1482,-8266
1781,2012,강동구,강일동,3461,3135,1457,741,1023,1101,981,1293,326,716,-78,-312
1782,2012,강동구,상일동,3973,4279,1871,1454,766,1053,1336,1772,-306,417,-287,-436
1783,2012,강동구,명일1동,4086,4422,2292,2018,846,1052,948,1352,-336,274,-206,-404
1784,2012,강동구,명일2동,2658,2513,1453,1142,554,652,651,719,145,311,-98,-68
1785,2012,강동구,고덕1동,2465,8260,862,4601,852,1734,751,1925,-5795,-3739,-882,-1174
1786,2012,강동구,고덕2동,2908,3208,1624,1176,552,702,732,1330,-300,448,-150,-598
1787,2012,강동구,암사2동,2695,2693,1090,1100,822,722,783,871,2,-10,100,-88
1788,2012,강동구,암사3동,2880,3113,1428,1273,790,866,662,974,-233,155,-76,-312
1789,2012,강동구,천호1동,5167,5447,2739,2412,1025,1151,1403,1884,-280,327,-126,-481
1790,2012,강동구,천호3동,4437,4930,1868,1902,1222,1292,1347,1736,-493,-34,-70,-389
1791,2012,강동구,성내1동,2854,3292,931,1101,1086,1047,837,1144,-438,-170,39,-307
1792,2012,강동구,성내2동,4874,5105,1601,1584,1826,1706,1447,1815,-231,17,120,-368
1793,2012,강동구,성내3동,4403,4556,1789,1639,1427,1314,1187,1603,-153,150,113,-416
1794,2012,강동구,둔촌1동,2849,3050,830,814,1268,1186,751,1050,-201,16,82,-299
1795,2012,강동구,둔촌2동,4076,4385,1636,1541,1192,1224,1248,1620,-309,95,-32,-372
1796,2012,강동구,암사1동,6099,6374,3102,2552,1450,1521,1547,2301,-275,550,-71,-754
1797,2012,강동구,천호2동,5960,6265,2482,2303,1718,1729,1760,2233,-305,179,-11,-473
1798,2012,강동구,길동,7373,7939,3041,2743,2135,1984,2197,3212,-566,298,151,-1015

In [364]:
diff_values.columns

Index(['기간', '자치구', '동', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출',
       '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출'],
      dtype='object')

In [22]:
hots = '연남동, 종로1.2.3.4가동, 종로5·6가동, 성수1가2동, 낙성대동, 망원1동, 망원2동, 사직동'.split(', ')
hots

['연남동', '종로1.2.3.4가동', '종로5·6가동', '성수1가2동', '낙성대동', '망원1동', '망원2동', '사직동']

In [23]:
len(hots)

8

In [24]:
hot = '연남동'
diff_values[diff_values['동'] == hot].set_index('기간').T

기간         2009  2010  2011  2012  2013  2014  2015  2016  2017
자치구         마포구   마포구   마포구   마포구   마포구   마포구   마포구   마포구   마포구
동           연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동
총전입        4149  3878  3748  3672  3516  3343  3284  3173  2976
총전출        4369  4344  4123  3956  3617  3898  3999  3809  3773
구내전입       1154  1088  1113  1093   993   919   905   829   742
구내전출       1301  1298  1229  1102   902  1094  1036   922   922
구간전입       1688  1645  1501  1385  1441  1252  1307  1141  1078
구간전출       1716  1701  1644  1619  1497  1516  1767  1754  1619
시/도간전입     1307  1145  1134  1194  1082  1172  1072  1203  1156
시/도간전출     1352  1345  1250  1235  1218  1288  1196  1133  1232
총전입-전출     -220  -466  -375  -284  -101  -555  -715  -636  -797
구내전입-전출    -147  -210  -116    -9    91  -175  -131   -93  -180
구간전입-전출     -28   -56  -143  -234   -56  -264  -460  -613  -541
시/도간전입-전출   -45  -200  -116   -41  -136  -116  -124    70   -76

In [25]:
now_hot = pd.DataFrame(columns=[year for year in range(2009, 2018)])

for hot in hots:
    df = diff_values[diff_values['동'] == hot].set_index('기간').T.iloc[1:, :]
#     print(df.head())
    now_hot = now_hot.append(df, ignore_index = True)
now_hot.head()

기간  2009  2010  2011  2012  2013  2014  2015  2016  2017
0    연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동
1   4149  3878  3748  3672  3516  3343  3284  3173  2976
2   4369  4344  4123  3956  3617  3898  3999  3809  3773
3   1154  1088  1113  1093   993   919   905   829   742
4   1301  1298  1229  1102   902  1094  1036   922   922

In [26]:
now_hot['지역'] = np.nan
for i in range(len(hots)):
    index = i*13
    for n in range(1, 13):
        now_hot['지역'][index+n] = now_hot.iloc[index,0]
now_hot.head()

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\rlath\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

기간  2009  2010  2011  2012  2013  2014  2015  2016  2017   지역
0    연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동  NaN
1   4149  3878  3748  3672  3516  3343  3284  3173  2976  연남동
2   4369  4344  4123  3956  3617  3898  3999  3809  3773  연남동
3   1154  1088  1113  1093   993   919   905   829   742  연남동
4   1301  1298  1229  1102   902  1094  1036   922   922  연남동

In [27]:
now_hot.head(13)

기간  2009  2010  2011  2012  2013  2014  2015  2016  2017   지역
0    연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동  NaN
1   4149  3878  3748  3672  3516  3343  3284  3173  2976  연남동
2   4369  4344  4123  3956  3617  3898  3999  3809  3773  연남동
3   1154  1088  1113  1093   993   919   905   829   742  연남동
4   1301  1298  1229  1102   902  1094  1036   922   922  연남동
5   1688  1645  1501  1385  1441  1252  1307  1141  1078  연남동
6   1716  1701  1644  1619  1497  1516  1767  1754  1619  연남동
7   1307  1145  1134  1194  1082  1172  1072  1203  1156  연남동
8   1352  1345  1250  1235  1218  1288  1196  1133  1232  연남동
9   -220  -466  -375  -284  -101  -555  -715  -636  -797  연남동
10  -147  -210  -116    -9    91  -175  -131   -93  -180  연남동
11   -28   -56  -143  -234   -56  -264  -460  -613  -541  연남동
12   -45  -200  -116   -41  -136  -116  -124    70   -76  연남동

In [28]:
len(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출'])

13

In [29]:
len(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']*len(hots))

104

In [30]:
diff_values.columns

Index(['기간', '자치구', '동', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출',
       '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출'],
      dtype='object')

In [31]:
now_hot['구분'] = list(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']*len(hots))

In [32]:
now_hot = now_hot[['지역', '구분', 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]]
now_hot

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,NaN,지역,연남동,연남동,연남동,연남동,연남동,연남동,연남동,연남동,연남동
1,연남동,총전입,4149,3878,3748,3672,3516,3343,3284,3173,2976
2,연남동,총전출,4369,4344,4123,3956,3617,3898,3999,3809,3773
3,연남동,구내전입,1154,1088,1113,1093,993,919,905,829,742
4,연남동,구내전출,1301,1298,1229,1102,902,1094,1036,922,922
5,연남동,구간전입,1688,1645,1501,1385,1441,1252,1307,1141,1078
6,연남동,구간전출,1716,1701,1644,1619,1497,1516,1767,1754,1619
7,연남동,시/도간전입,1307,1145,1134,1194,1082,1172,1072,1203,1156
8,연남동,시/도간전출,1352,1345,1250,1235,1218,1288,1196,1133,1232
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
13,NaN,지역,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동
14,종로1.2.3.4가동,총전입,1880,1815,1814,1732,1686,1951,1872,1757,1690
15,종로1.2.3.4가동,총전출,1882,1876,1855,1677,1756,1892,1922,1909,1774
16,종로1.2.3.4가동,구내전입,199,229,189,180,183,190,184,128,136
17,종로1.2.3.4가동,구내전출,218,212,228,231,218,224,287,250,264
18,종로1.2.3.4가동,구간전입,950,889,950,844,839,808,821,856,757
19,종로1.2.3.4가동,구간전출,1016,1014,1003,891,926,996,960,974,870
20,종로1.2.3.4가동,시/도간전입,731,697,675,708,664,953,867,773,797
21,종로1.2.3.4가동,시/도간전출,648,650,624,555,612,672,675,685,640
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
26,NaN,지역,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동
27,종로5·6가동,총전입,1105,1126,965,1038,892,870,1129,920,989
28,종로5·6가동,총전출,1290,1276,1107,1055,1069,1032,1142,1137,1093
29,종로5·6가동,구내전입,235,235,194,225,203,155,175,163,174
...,...,...,...,...,...,...,...,...,...,...,...
74,망원1동,총전입-전출,-288,-362,-475,-422,-411,-952,-938,-539,-494
75,망원1동,구내전입-전출,121,-81,52,160,233,-293,-97,126,38
76,망원1동,구간전입-전출,-144,35,-168,-203,-172,-392,-424,-395,-291
77,망원1동,시/도간전입-전출,-265,-316,-359,-379,-472,-267,-417,-270,-241
78,NaN,지역,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동
79,망원2동,총전입,3974,3556,3314,2922,2997,3155,3099,2978,2424
80,망원2동,총전출,3673,4108,3631,3426,3406,3302,3513,3388,2952
81,망원2동,구내전입,1692,1472,1401,1291,1322,1482,1464,1426,1009
82,망원2동,구내전출,1305,1412,1199,1076,1177,1153,1194,1124,979
83,망원2동,구간전입,1313,1141,1071,832,967,903,885,793,741
84,망원2동,구간전출,1291,1308,1231,1127,1164,1057,1243,1181,981
85,망원2동,시/도간전입,969,943,842,799,708,770,750,759,674
86,망원2동,시/도간전출,1077,1388,1201,1223,1065,1092,1076,1083,992
87,망원2동,총전입-전출,301,-552,-317,-504,-409,-147,-414,-410,-528
88,망원2동,구내전입-전출,387,60,202,215,145,329,270,302,30
89,망원2동,구간전입-전출,22,-167,-160,-295,-197,-154,-358,-388,-240
90,망원2동,시/도간전입-전출,-108,-445,-359,-424,-357,-322,-326,-324,-318
91,NaN,지역,사직동,사직동,사직동,사직동,사직동,사직동,사직동,사직동,사직동
92,사직동,총전입,2140,2041,2115,1811,1665,1694,1708,1725,1733
93,사직동,총전출,2076,2261,2215,1979,1872,1840,1840,1790,1993
94,사직동,구내전입,448,433,467,415,406,377,294,290,315
95,사직동,구내전출,402,445,487,417,360,360,364,301,517
96,사직동,구간전입,1087,1017,1047,924,828,833,967,928,899
97,사직동,구간전출,1160,1209,1133,997,990,1003,1030,988,993
98,사직동,시/도간전입,605,591,601,472,431,484,447,507,519
99,사직동,시/도간전출,514,607,595,565,522,477,446,501,483
100,사직동,총전입-전출,64,-220,-100,-168,-207,-146,-132,-65,-260
101,사직동,구내전입-전출,46,-12,-20,-2,46,17,-70,-11,-202
102,사직동,구간전입-전출,-73,-192,-86,-73,-162,-170,-63,-60,-94
103,사직동,시/도간전입-전출,91,-16,6,-93,-91,7,1,6,36

In [33]:
now_hot = now_hot.dropna()

In [34]:
now_hot.head(30)

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
1,연남동,총전입,4149,3878,3748,3672,3516,3343,3284,3173,2976
2,연남동,총전출,4369,4344,4123,3956,3617,3898,3999,3809,3773
3,연남동,구내전입,1154,1088,1113,1093,993,919,905,829,742
4,연남동,구내전출,1301,1298,1229,1102,902,1094,1036,922,922
5,연남동,구간전입,1688,1645,1501,1385,1441,1252,1307,1141,1078
6,연남동,구간전출,1716,1701,1644,1619,1497,1516,1767,1754,1619
7,연남동,시/도간전입,1307,1145,1134,1194,1082,1172,1072,1203,1156
8,연남동,시/도간전출,1352,1345,1250,1235,1218,1288,1196,1133,1232
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
14,종로1.2.3.4가동,총전입,1880,1815,1814,1732,1686,1951,1872,1757,1690
15,종로1.2.3.4가동,총전출,1882,1876,1855,1677,1756,1892,1922,1909,1774
16,종로1.2.3.4가동,구내전입,199,229,189,180,183,190,184,128,136
17,종로1.2.3.4가동,구내전출,218,212,228,231,218,224,287,250,264
18,종로1.2.3.4가동,구간전입,950,889,950,844,839,808,821,856,757
19,종로1.2.3.4가동,구간전출,1016,1014,1003,891,926,996,960,974,870
20,종로1.2.3.4가동,시/도간전입,731,697,675,708,664,953,867,773,797
21,종로1.2.3.4가동,시/도간전출,648,650,624,555,612,672,675,685,640
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
27,종로5·6가동,총전입,1105,1126,965,1038,892,870,1129,920,989
28,종로5·6가동,총전출,1290,1276,1107,1055,1069,1032,1142,1137,1093
29,종로5·6가동,구내전입,235,235,194,225,203,155,175,163,174
30,종로5·6가동,구내전출,300,291,208,204,258,212,272,281,219
31,종로5·6가동,구간전입,516,552,405,447,374,354,410,342,363
32,종로5·6가동,구간전출,605,659,565,511,519,487,492,493,516

In [35]:
now_hot[now_hot['구분'] == '총전입-전출']

기간            지역      구분  2009  2010  2011  2012  2013  2014  2015  2016  2017
9            연남동  총전입-전출  -220  -466  -375  -284  -101  -555  -715  -636  -797
22   종로1.2.3.4가동  총전입-전출    -2   -61   -41    55   -70    59   -50  -152   -84
35       종로5·6가동  총전입-전출  -185  -150  -142   -17  -177  -162   -13  -217  -104
48        성수1가2동  총전입-전출  -529  -465  -451  -310  -526  -596  -754  -590  -617
61          낙성대동  총전입-전출  -362  -117  -188  -137  -153  -269  -235  -179  -377
74          망원1동  총전입-전출  -288  -362  -475  -422  -411  -952  -938  -539  -494
87          망원2동  총전입-전출   301  -552  -317  -504  -409  -147  -414  -410  -528
100          사직동  총전입-전출    64  -220  -100  -168  -207  -146  -132   -65  -260

In [36]:
diff_values[diff_values['자치구'].str.contains(r'(합계|총계)')]

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264
450,2010,합계,합계,1733015,1848038,520345,520345,679363,679363,533307,648330,-115023,0,0,-115023
900,2011,합계,합계,1721748,1834806,543807,543807,671315,671315,506626,619684,-113058,0,0,-113058
1350,2012,총계,총계,1555281,1658928,473458,473458,595842,595842,485981,589628,-103647,0,0,-103647
1799,2013,합계,합계,1520090,1620640,468394,468394,584614,584614,467082,567632,-100550,0,0,-100550
2248,2014,합계,합계,1573594,1661425,495401,495401,602622,602622,475571,563402,-87831,0,0,-87831
2697,2015,합계,합계,1589431,1726687,524267,524267,605262,605262,459902,597158,-137256,0,0,-137256
3147,2016,합계,합계,1515602,1655859,487722,487722,574193,574193,453687,593944,-140257,0,0,-140257
3597,2017,합계,합계,1472937,1571423,454536,454536,564271,564271,454130,552616,-98486,0,0,-98486

In [510]:
diff_values.tail(2)

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
4045,2017,강동구,천호2동,6499,6025,2679,2328,2083,1492,1737,2205,474,351,591,-468
4046,2017,강동구,길동,7512,8644,3498,3430,1864,1881,2150,3333,-1132,68,-17,-1183

In [515]:
total_means = [np.round(-52264 / 450, 4),
np.round(-115023 / 450, 4),
np.round(-113058 / (1799-900), 4),
np.round(-100550 / (2248-1799), 4),
np.round(-87831 / (2697-2248), 4),
np.round(-137256 / (3147-2697), 4),
np.round(-140257 / (3597-3147), 4),
np.round(-98486 / (4046-3597), 4)]

In [514]:
changes_now_hot = now_hot[now_hot['구분'].str.contains(r'(총전입-전출|구내전입-전출|구간전입-전출|시/도간전입-전출)')]
changes_now_hot

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
35,종로5·6가동,총전입-전출,-185,-150,-142,-17,-177,-162,-13,-217,-104
36,종로5·6가동,구내전입-전출,-65,-56,-14,21,-55,-57,-97,-118,-45
37,종로5·6가동,구간전입-전출,-89,-107,-160,-64,-145,-133,-82,-151,-153
38,종로5·6가동,시/도간전입-전출,-31,13,32,26,23,28,166,52,94
48,성수1가2동,총전입-전출,-529,-465,-451,-310,-526,-596,-754,-590,-617
49,성수1가2동,구내전입-전출,-28,-4,-5,-27,44,-94,-228,-160,-229
50,성수1가2동,구간전입-전출,-303,-298,-370,-95,-321,-241,-280,-181,-285
51,성수1가2동,시/도간전입-전출,-198,-163,-76,-188,-249,-261,-246,-249,-103
61,낙성대동,총전입-전출,-362,-117,-188,-137,-153,-269,-235,-179,-377
62,낙성대동,구내전입-전출,-160,-107,-225,-213,-256,-155,-216,-242,-457
63,낙성대동,구간전입-전출,-510,-155,-235,-311,-208,-376,-186,-275,-333
64,낙성대동,시/도간전입-전출,308,145,272,387,311,262,167,338,413
74,망원1동,총전입-전출,-288,-362,-475,-422,-411,-952,-938,-539,-494
75,망원1동,구내전입-전출,121,-81,52,160,233,-293,-97,126,38
76,망원1동,구간전입-전출,-144,35,-168,-203,-172,-392,-424,-395,-291
77,망원1동,시/도간전입-전출,-265,-316,-359,-379,-472,-267,-417,-270,-241
87,망원2동,총전입-전출,301,-552,-317,-504,-409,-147,-414,-410,-528
88,망원2동,구내전입-전출,387,60,202,215,145,329,270,302,30
89,망원2동,구간전입-전출,22,-167,-160,-295,-197,-154,-358,-388,-240
90,망원2동,시/도간전입-전출,-108,-445,-359,-424,-357,-322,-326,-324,-318
100,사직동,총전입-전출,64,-220,-100,-168,-207,-146,-132,-65,-260
101,사직동,구내전입-전출,46,-12,-20,-2,46,17,-70,-11,-202
102,사직동,구간전입-전출,-73,-192,-86,-73,-162,-170,-63,-60,-94
103,사직동,시/도간전입-전출,91,-16,6,-93,-91,7,1,6,36

In [ ]:
['지역', '구분', 2009 , 2010 : 	2011	2012	2013	2014	2015	2016	2017]

In [ ]:
changes_now_hot.append()

In [516]:
now_hot.to_csv('hots.csv', index=False)

# 10월 1일

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
now_hot = pd.read_csv('hots.csv')
now_hot.head()

    지역    구분  2009  2010  2011  2012  2013  2014  2015  2016  2017
0  연남동   총전입  4149  3878  3748  3672  3516  3343  3284  3173  2976
1  연남동   총전출  4369  4344  4123  3956  3617  3898  3999  3809  3773
2  연남동  구내전입  1154  1088  1113  1093   993   919   905   829   742
3  연남동  구내전출  1301  1298  1229  1102   902  1094  1036   922   922
4  연남동  구간전입  1688  1645  1501  1385  1441  1252  1307  1141  1078

In [68]:
changes_now_hot = now_hot[now_hot['구분'].str.contains(r'(총전입-전출|구내전입-전출|구간전입-전출|시/도간전입-전출)')].copy(deep=True)
changes_now_hot

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
35,종로5·6가동,총전입-전출,-185,-150,-142,-17,-177,-162,-13,-217,-104
36,종로5·6가동,구내전입-전출,-65,-56,-14,21,-55,-57,-97,-118,-45
37,종로5·6가동,구간전입-전출,-89,-107,-160,-64,-145,-133,-82,-151,-153
38,종로5·6가동,시/도간전입-전출,-31,13,32,26,23,28,166,52,94
48,성수1가2동,총전입-전출,-529,-465,-451,-310,-526,-596,-754,-590,-617
49,성수1가2동,구내전입-전출,-28,-4,-5,-27,44,-94,-228,-160,-229
50,성수1가2동,구간전입-전출,-303,-298,-370,-95,-321,-241,-280,-181,-285
51,성수1가2동,시/도간전입-전출,-198,-163,-76,-188,-249,-261,-246,-249,-103
61,낙성대동,총전입-전출,-362,-117,-188,-137,-153,-269,-235,-179,-377
62,낙성대동,구내전입-전출,-160,-107,-225,-213,-256,-155,-216,-242,-457
63,낙성대동,구간전입-전출,-510,-155,-235,-311,-208,-376,-186,-275,-333
64,낙성대동,시/도간전입-전출,308,145,272,387,311,262,167,338,413
74,망원1동,총전입-전출,-288,-362,-475,-422,-411,-952,-938,-539,-494
75,망원1동,구내전입-전출,121,-81,52,160,233,-293,-97,126,38
76,망원1동,구간전입-전출,-144,35,-168,-203,-172,-392,-424,-395,-291
77,망원1동,시/도간전입-전출,-265,-316,-359,-379,-472,-267,-417,-270,-241
87,망원2동,총전입-전출,301,-552,-317,-504,-409,-147,-414,-410,-528
88,망원2동,구내전입-전출,387,60,202,215,145,329,270,302,30
89,망원2동,구간전입-전출,22,-167,-160,-295,-197,-154,-358,-388,-240
90,망원2동,시/도간전입-전출,-108,-445,-359,-424,-357,-322,-326,-324,-318
100,사직동,총전입-전출,64,-220,-100,-168,-207,-146,-132,-65,-260
101,사직동,구내전입-전출,46,-12,-20,-2,46,17,-70,-11,-202
102,사직동,구간전입-전출,-73,-192,-86,-73,-162,-170,-63,-60,-94
103,사직동,시/도간전입-전출,91,-16,6,-93,-91,7,1,6,36

In [69]:
index = ['지역', '구분', 2009 , 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
total_means = [
    '지역', '평균',
    np.round(-52264 / 450, 2),
    np.round(-115023 / 450, 2),
    np.round(-113058 / 450, 2),
    np.round(-103647 / 449, 2),
    np.round(-100550 / 449, 2),
    np.round(-87831 / 449, 2),
    np.round(-137256 / 450, 2),
    np.round(-140257 / 450, 2),
    np.round(-98486 / 450, 2)
]
len(total_means), len(index)

(11, 11)

In [71]:
temp = dict()
for i, m in zip(index, total_means):
    temp[i] = m
temp

{'지역': '지역',
 '구분': '평균',
 2009: -116.14,
 2010: -255.61,
 2011: -251.24,
 2012: -230.84,
 2013: -223.94,
 2014: -195.61,
 2015: -305.01,
 2016: -311.68,
 2017: -218.86}

In [70]:
changes_now_hot.columns

Index(['지역', '구분', 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017], dtype='object', name='기간')

In [72]:
changes_now_hot = changes_now_hot.append(temp, ignore_index=True)
changes_now_hot

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
1,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
2,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
3,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
4,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
5,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
6,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
7,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
8,종로5·6가동,총전입-전출,-185,-150,-142,-17,-177,-162,-13,-217,-104
9,종로5·6가동,구내전입-전출,-65,-56,-14,21,-55,-57,-97,-118,-45
10,종로5·6가동,구간전입-전출,-89,-107,-160,-64,-145,-133,-82,-151,-153
11,종로5·6가동,시/도간전입-전출,-31,13,32,26,23,28,166,52,94
12,성수1가2동,총전입-전출,-529,-465,-451,-310,-526,-596,-754,-590,-617
13,성수1가2동,구내전입-전출,-28,-4,-5,-27,44,-94,-228,-160,-229
14,성수1가2동,구간전입-전출,-303,-298,-370,-95,-321,-241,-280,-181,-285
15,성수1가2동,시/도간전입-전출,-198,-163,-76,-188,-249,-261,-246,-249,-103
16,낙성대동,총전입-전출,-362,-117,-188,-137,-153,-269,-235,-179,-377
17,낙성대동,구내전입-전출,-160,-107,-225,-213,-256,-155,-216,-242,-457
18,낙성대동,구간전입-전출,-510,-155,-235,-311,-208,-376,-186,-275,-333
19,낙성대동,시/도간전입-전출,308,145,272,387,311,262,167,338,413
20,망원1동,총전입-전출,-288,-362,-475,-422,-411,-952,-938,-539,-494
21,망원1동,구내전입-전출,121,-81,52,160,233,-293,-97,126,38
22,망원1동,구간전입-전출,-144,35,-168,-203,-172,-392,-424,-395,-291
23,망원1동,시/도간전입-전출,-265,-316,-359,-379,-472,-267,-417,-270,-241
24,망원2동,총전입-전출,301,-552,-317,-504,-409,-147,-414,-410,-528
25,망원2동,구내전입-전출,387,60,202,215,145,329,270,302,30
26,망원2동,구간전입-전출,22,-167,-160,-295,-197,-154,-358,-388,-240
27,망원2동,시/도간전입-전출,-108,-445,-359,-424,-357,-322,-326,-324,-318
28,사직동,총전입-전출,64,-220,-100,-168,-207,-146,-132,-65,-260
29,사직동,구내전입-전출,46,-12,-20,-2,46,17,-70,-11,-202
30,사직동,구간전입-전출,-73,-192,-86,-73,-162,-170,-63,-60,-94
31,사직동,시/도간전입-전출,91,-16,6,-93,-91,7,1,6,36
32,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86

In [74]:
changes_now_hot = changes_now_hot.reindex([32, 0, 1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22, 22,23,24,25,26,27,28,29,30,31])
changes_now_hot.to_csv('seoul_in_out_now_hot_changes.csv', index=False)

# 어게인~!

In [75]:
now_hot_changes = pd.read_csv('seoul_in_out_now_hot.csv')
now_hot_changes

,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
1,연남동,총전입-전출,-220.00,-466.00,-375.00,-284.00,-101.00,-555.00,-715.00,-636.00,-797.00
2,연남동,구내전입-전출,-147.00,-210.00,-116.00,-9.00,91.00,-175.00,-131.00,-93.00,-180.00
3,연남동,구간전입-전출,-28.00,-56.00,-143.00,-234.00,-56.00,-264.00,-460.00,-613.00,-541.00
4,연남동,시/도간전입-전출,-45.00,-200.00,-116.00,-41.00,-136.00,-116.00,-124.00,70.00,-76.00
5,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
6,종로1.2.3.4가동,총전입-전출,-2.00,-61.00,-41.00,55.00,-70.00,59.00,-50.00,-152.00,-84.00
7,종로1.2.3.4가동,구내전입-전출,-19.00,17.00,-39.00,-51.00,-35.00,-34.00,-103.00,-122.00,-128.00
8,종로1.2.3.4가동,구간전입-전출,-66.00,-125.00,-53.00,-47.00,-87.00,-188.00,-139.00,-118.00,-113.00
9,종로1.2.3.4가동,시/도간전입-전출,83.00,47.00,51.00,153.00,52.00,281.00,192.00,88.00,157.00
10,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
11,종로5·6가동,총전입-전출,-185.00,-150.00,-142.00,-17.00,-177.00,-162.00,-13.00,-217.00,-104.00
12,종로5·6가동,구내전입-전출,-65.00,-56.00,-14.00,21.00,-55.00,-57.00,-97.00,-118.00,-45.00
13,종로5·6가동,구간전입-전출,-89.00,-107.00,-160.00,-64.00,-145.00,-133.00,-82.00,-151.00,-153.00
14,종로5·6가동,시/도간전입-전출,-31.00,13.00,32.00,26.00,23.00,28.00,166.00,52.00,94.00
15,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
16,성수1가2동,총전입-전출,-529.00,-465.00,-451.00,-310.00,-526.00,-596.00,-754.00,-590.00,-617.00
17,성수1가2동,구내전입-전출,-28.00,-4.00,-5.00,-27.00,44.00,-94.00,-228.00,-160.00,-229.00
18,성수1가2동,구간전입-전출,-303.00,-298.00,-370.00,-95.00,-321.00,-241.00,-280.00,-181.00,-285.00
19,성수1가2동,시/도간전입-전출,-198.00,-163.00,-76.00,-188.00,-249.00,-261.00,-246.00,-249.00,-103.00
20,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
21,낙성대동,총전입-전출,-362.00,-117.00,-188.00,-137.00,-153.00,-269.00,-235.00,-179.00,-377.00
22,낙성대동,구내전입-전출,-160.00,-107.00,-225.00,-213.00,-256.00,-155.00,-216.00,-242.00,-457.00
23,낙성대동,구간전입-전출,-510.00,-155.00,-235.00,-311.00,-208.00,-376.00,-186.00,-275.00,-333.00
24,낙성대동,시/도간전입-전출,308.00,145.00,272.00,387.00,311.00,262.00,167.00,338.00,413.00
25,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
26,망원1동,총전입-전출,-288.00,-362.00,-475.00,-422.00,-411.00,-952.00,-938.00,-539.00,-494.00
27,망원1동,구내전입-전출,121.00,-81.00,52.00,160.00,233.00,-293.00,-97.00,126.00,38.00
28,망원1동,구간전입-전출,-144.00,35.00,-168.00,-203.00,-172.00,-392.00,-424.00,-395.00,-291.00
29,망원1동,구간전입-전출,-144.00,35.00,-168.00,-203.00,-172.00,-392.00,-424.00,-395.00,-291.00
30,망원1동,시/도간전입-전출,-265.00,-316.00,-359.00,-379.00,-472.00,-267.00,-417.00,-270.00,-241.00
31,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
32,망원2동,총전입-전출,301.00,-552.00,-317.00,-504.00,-409.00,-147.00,-414.00,-410.00,-528.00
33,망원2동,구내전입-전출,387.00,60.00,202.00,215.00,145.00,329.00,270.00,302.00,30.00
34,망원2동,구간전입-전출,22.00,-167.00,-160.00,-295.00,-197.00,-154.00,-358.00,-388.00,-240.00
35,망원2동,시/도간전입-전출,-108.00,-445.00,-359.00,-424.00,-357.00,-322.00,-326.00,-324.00,-318.00
36,지역,평균,-116.14,-255.61,-251.24,-230.84,-223.94,-195.61,-305.01,-311.68,-218.86
37,사직동,총전입-전출,64.00,-220.00,-100.00,-168.00,-207.00,-146.00,-132.00,-65.00,-260.00
38,사직동,구내전입-전출,46.00,-12.00,-20.00,-2.00,46.00,17.00,-70.00,-11.00,-202.00
39,사직동,구간전입-전출,-73.00,-192.00,-86.00,-73.00,-162.00,-170.00,-63.00,-60.00,-94.00
40,사직동,시/도간전입-전출,91.00,-16.00,6.00,-93.00,-91.00,7.00,1.00,6.00,36.00

In [78]:
diff_values[diff_values['동'].str.contains(r'상도[1234]동')]

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
326,2009,동작구,상도1동,7270,7660,1262,1326,3128,3679,2880,2655,-390,-64,-551,225
327,2009,동작구,상도2동,5083,4977,1779,1484,1855,1927,1449,1566,106,295,-72,-117
328,2009,동작구,상도3동,4529,4250,1694,1381,1556,1473,1279,1396,279,313,83,-117
329,2009,동작구,상도4동,4620,4886,1680,1509,1568,1701,1372,1676,-266,171,-133,-304
776,2010,동작구,상도1동,7017,7438,1164,1320,2953,3188,2900,2930,-421,-156,-235,-30
777,2010,동작구,상도2동,5240,5198,1829,1681,2008,1843,1403,1674,42,148,165,-271
778,2010,동작구,상도3동,4263,4452,1640,1423,1477,1424,1146,1605,-189,217,53,-459
779,2010,동작구,상도4동,4819,4969,1826,1526,1673,1675,1320,1768,-150,300,-2,-448
1226,2011,동작구,상도1동,6944,7305,1284,1396,2971,3276,2689,2633,-361,-112,-305,56
1227,2011,동작구,상도2동,4670,5427,1639,1827,1676,1870,1355,1730,-757,-188,-194,-375
1228,2011,동작구,상도3동,4228,4354,1646,1412,1437,1444,1145,1498,-126,234,-7,-353
1229,2011,동작구,상도4동,4593,4988,1849,1607,1598,1665,1146,1716,-395,242,-67,-570
1675,2012,동작구,상도1동,9829,6670,1684,1319,5024,2793,3121,2558,3159,365,2231,563
1676,2012,동작구,상도2동,4415,4734,1472,1707,1640,1498,1303,1529,-319,-235,142,-226
1677,2012,동작구,상도3동,3769,4037,1432,1294,1250,1346,1087,1397,-268,138,-96,-310
1678,2012,동작구,상도4동,4102,4380,1536,1403,1444,1456,1122,1521,-278,133,-12,-399
2124,2013,동작구,상도1동,10775,7371,1851,1287,5257,3251,3667,2833,3404,564,2006,834
2125,2013,동작구,상도2동,4426,4771,1534,1775,1481,1585,1411,1411,-345,-241,-104,0
2126,2013,동작구,상도3동,3950,3938,1546,1327,1362,1254,1042,1357,12,219,108,-315
2127,2013,동작구,상도4동,4226,4551,1662,1436,1499,1525,1065,1590,-325,226,-26,-525
2573,2014,동작구,상도1동,8529,7950,1538,1357,3653,3535,3338,3058,579,181,118,280
2574,2014,동작구,상도2동,4312,4713,1556,1522,1518,1634,1238,1557,-401,34,-116,-319
2575,2014,동작구,상도3동,4069,4146,1545,1304,1448,1516,1076,1326,-77,241,-68,-250
2576,2014,동작구,상도4동,4248,4358,1691,1411,1469,1495,1088,1452,-110,280,-26,-364
3022,2015,동작구,상도1동,8401,8648,1897,1564,3385,3865,3119,3219,-247,333,-480,-100
3023,2015,동작구,상도2동,4379,5613,1674,2010,1454,1950,1251,1653,-1234,-336,-496,-402
3024,2015,동작구,상도3동,4273,4333,1888,1493,1363,1411,1022,1429,-60,395,-48,-407
3025,2015,동작구,상도4동,4618,4736,1876,1638,1636,1492,1106,1606,-118,238,144,-500
3472,2016,동작구,상도1동,7566,8377,1289,1583,3095,3729,3182,3065,-811,-294,-634,117
3473,2016,동작구,상도2동,7437,4705,2834,1560,3003,1510,1600,1635,2732,1274,1493,-35
3474,2016,동작구,상도3동,4520,4128,1712,1554,1713,1237,1095,1337,392,158,476,-242
3475,2016,동작구,상도4동,4578,4412,1655,1505,1791,1360,1132,1547,166,150,431,-415
3922,2017,동작구,상도1동,7596,7805,1340,1302,3020,3446,3236,3057,-209,38,-426,179
3923,2017,동작구,상도2동,4381,4716,1579,1575,1508,1627,1294,1514,-335,4,-119,-220
3924,2017,동작구,상도3동,4034,3813,1541,1210,1437,1276,1056,1327,221,331,161,-271
3925,2017,동작구,상도4동,4181,4417,1690,1439,1430,1474,1061,1504,-236,251,-44,-443

In [84]:
diff_values[diff_values['동'].str.contains(r'명일')]

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
434,2009,강동구,명일1동,5590,6183,2638,3395,1410,1198,1542,1590,-593,-757,212,-48
435,2009,강동구,명일2동,3497,3557,1709,1878,812,774,976,905,-60,-169,38,71
884,2010,강동구,명일1동,4364,4786,2059,2263,1070,1073,1235,1450,-422,-204,-3,-215
885,2010,강동구,명일2동,2622,2871,1213,1337,717,667,692,867,-249,-124,50,-175
1334,2011,강동구,명일1동,4732,5127,2351,2675,1089,953,1292,1499,-395,-324,136,-207
1335,2011,강동구,명일2동,2639,2831,1343,1390,616,712,680,729,-192,-47,-96,-49
1783,2012,강동구,명일1동,4086,4422,2292,2018,846,1052,948,1352,-336,274,-206,-404
1784,2012,강동구,명일2동,2658,2513,1453,1142,554,652,651,719,145,311,-98,-68
2232,2013,강동구,명일1동,3901,4259,2073,2120,812,855,1016,1284,-358,-47,-43,-268
2233,2013,강동구,명일2동,2429,2591,1235,1176,608,616,586,799,-162,59,-8,-213
2681,2014,강동구,명일1동,3761,4286,2004,2030,819,947,938,1309,-525,-26,-128,-371
2682,2014,강동구,명일2동,2514,2679,1341,1164,597,632,576,883,-165,177,-35,-307
3131,2015,강동구,명일1동,3192,7952,1885,4337,580,1399,727,2216,-4760,-2452,-819,-1489
3132,2015,강동구,명일2동,2828,2996,1726,1295,404,684,698,1017,-168,431,-280,-319
3581,2016,강동구,명일1동,3150,3634,1932,1580,527,633,691,1421,-484,352,-106,-730
3582,2016,강동구,명일2동,2724,2949,1652,1096,487,655,585,1198,-225,556,-168,-613
4031,2017,강동구,명일1동,3235,3734,1915,1941,572,637,748,1156,-499,-26,-65,-408
4032,2017,강동구,명일2동,2542,2818,1465,1358,494,553,583,907,-276,107,-59,-324

In [93]:
un_hips = '상도1동,상도2동,상도3동,상도4동,상계1동,상계2동,상계5동,상계8동,상계9동,상계10동,상계3.4동,상계6.7동,명일1동,명일2동'.split(',')

In [94]:
un_hip = pd.DataFrame(columns=[year for year in range(2009, 2018)])

for u in un_hips:
    df = diff_values[diff_values['동'] == u].set_index('기간').T.iloc[1:, :]
#     print(df.head())
    un_hip = un_hip.append(df, ignore_index = True)
un_hip.head()

기간  2009  2010  2011  2012   2013  2014  2015  2016  2017
0   상도1동  상도1동  상도1동  상도1동   상도1동  상도1동  상도1동  상도1동  상도1동
1   7270  7017  6944  9829  10775  8529  8401  7566  7596
2   7660  7438  7305  6670   7371  7950  8648  8377  7805
3   1262  1164  1284  1684   1851  1538  1897  1289  1340
4   1326  1320  1396  1319   1287  1357  1564  1583  1302

In [95]:
un_hip['지역'] = np.nan
for i in range(len(un_hips)):
    index = i*13
    for n in range(1, 13):
        un_hip['지역'][index+n] = un_hip.iloc[index,0]
un_hip.head()

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\rlath\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

기간  2009  2010  2011  2012   2013  2014  2015  2016  2017    지역
0   상도1동  상도1동  상도1동  상도1동   상도1동  상도1동  상도1동  상도1동  상도1동   NaN
1   7270  7017  6944  9829  10775  8529  8401  7566  7596  상도1동
2   7660  7438  7305  6670   7371  7950  8648  8377  7805  상도1동
3   1262  1164  1284  1684   1851  1538  1897  1289  1340  상도1동
4   1326  1320  1396  1319   1287  1357  1564  1583  1302  상도1동

In [96]:
un_hip['구분'] = list(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']*len(un_hips))
un_hip = un_hip[['지역', '구분', 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]]
un_hip

기간       지역         구분  2009  2010  2011  2012   2013  2014   2015  2016  2017
0       NaN         지역  상도1동  상도1동  상도1동  상도1동   상도1동  상도1동   상도1동  상도1동  상도1동
1      상도1동        총전입  7270  7017  6944  9829  10775  8529   8401  7566  7596
2      상도1동        총전출  7660  7438  7305  6670   7371  7950   8648  8377  7805
3      상도1동       구내전입  1262  1164  1284  1684   1851  1538   1897  1289  1340
4      상도1동       구내전출  1326  1320  1396  1319   1287  1357   1564  1583  1302
5      상도1동       구간전입  3128  2953  2971  5024   5257  3653   3385  3095  3020
6      상도1동       구간전출  3679  3188  3276  2793   3251  3535   3865  3729  3446
7      상도1동     시/도간전입  2880  2900  2689  3121   3667  3338   3119  3182  3236
8      상도1동     시/도간전출  2655  2930  2633  2558   2833  3058   3219  3065  3057
9      상도1동     총전입-전출  -390  -421  -361  3159   3404   579   -247  -811  -209
10     상도1동    구내전입-전출   -64  -156  -112   365    564   181    333  -294    38
11     상도1동    구간전입-전출  -551  -235  -305  2231   2006   118   -480  -634  -426
12     상도1동  시/도간전입-전출   225   -30    56   563    834   280   -100   117   179
13      NaN         지역  상도2동  상도2동  상도2동  상도2동   상도2동  상도2동   상도2동  상도2동  상도2동
14     상도2동        총전입  5083  5240  4670  4415   4426  4312   4379  7437  4381
15     상도2동        총전출  4977  5198  5427  4734   4771  4713   5613  4705  4716
16     상도2동       구내전입  1779  1829  1639  1472   1534  1556   1674  2834  1579
17     상도2동       구내전출  1484  1681  1827  1707   1775  1522   2010  1560  1575
18     상도2동       구간전입  1855  2008  1676  1640   1481  1518   1454  3003  1508
19     상도2동       구간전출  1927  1843  1870  1498   1585  1634   1950  1510  1627
20     상도2동     시/도간전입  1449  1403  1355  1303   1411  1238   1251  1600  1294
21     상도2동     시/도간전출  1566  1674  1730  1529   1411  1557   1653  1635  1514
22     상도2동     총전입-전출   106    42  -757  -319   -345  -401  -1234  2732  -335
23     상도2동    구내전입-전출   295   148  -188  -235   -241    34   -336  1274     4
24     상도2동    구간전입-전출   -72   165  -194   142   -104  -116   -496  1493  -119
25     상도2동  시/도간전입-전출  -117  -271  -375  -226      0  -319   -402   -35  -220
26      NaN         지역  상도3동  상도3동  상도3동  상도3동   상도3동  상도3동   상도3동  상도3동  상도3동
27     상도3동        총전입  4529  4263  4228  3769   3950  4069   4273  4520  4034
28     상도3동        총전출  4250  4452  4354  4037   3938  4146   4333  4128  3813
29     상도3동       구내전입  1694  1640  1646  1432   1546  1545   1888  1712  1541
..      ...        ...   ...   ...   ...   ...    ...   ...    ...   ...   ...
152  상계6.7동     총전입-전출  -712  -629  -710  -626   -648  -636   -787   496  -665
153  상계6.7동    구내전입-전출  -270  -273  -291  -115   -345  -335    -70   567   161
154  상계6.7동    구간전입-전출  -226    65   -75    60     83   153     62   620  -141
155  상계6.7동  시/도간전입-전출  -216  -421  -344  -571   -386  -454   -779  -691  -685
156     NaN         지역  명일1동  명일1동  명일1동  명일1동   명일1동  명일1동   명일1동  명일1동  명일1동
157    명일1동        총전입  5590  4364  4732  4086   3901  3761   3192  3150  3235
158    명일1동        총전출  6183  4786  5127  4422   4259  4286   7952  3634  3734
159    명일1동       구내전입  2638  2059  2351  2292   2073  2004   1885  1932  1915
160    명일1동       구내전출  3395  2263  2675  2018   2120  2030   4337  1580  1941
161    명일1동       구간전입  1410  1070  1089   846    812   819    580   527   572
162    명일1동       구간전출  1198  1073   953  1052    855   947   1399   633   637
163    명일1동     시/도간전입  1542  1235  1292   948   1016   938    727   691   748
164    명일1동     시/도간전출  1590  1450  1499  1352   1284  1309   2216  1421  1156
165    명일1동     총전입-전출  -593  -422  -395  -336   -358  -525  -4760  -484  -499
166    명일1동    구내전입-전출  -757  -204  -324   274    -47   -26  -2452   352   -26
167    명일1동    구간전입-전출   212    -3   136  -206    -43  -128   -819  -106   -65
168    명일1동  시/도간전입-전출   -48  -215  -207  -404   -268  -371  -1489  -730  -408
169     NaN         지역  명일2동  명일2동  명일2동  명일2동   명일2동  명일2동   명일2동  명일2동  명일2동
170    명일2동        총전입  3497  2622  2639  2658   2429  2514   2828  2724  2542
171    명일2동        총전출  3557  2871  2831  2513   2591  2679   2996  2949  2818
172    명일2동       구내전입  1709  1213  1343  1453   1235  1341   1726  1652  1465
173    명일2동       구내전출  1878  1337  1390  1142   1176  1164   1295  1096  1358
174    명일2동       구간전입   812   717   616   554    608   597    404   487   494
175    명일2동       구간전출   774   667   712   652    616   632    684   655   553
176    명일2동     시/도간전입   976   692   680   651    586   576    698   585   583
177    명일2동     시/도간전출   905   867   729   719    799   883   1017  1198   907
178    명일2동     총전입-전출   -60  -249  -192   145   -162  -165   -168  -225  -276
179    명일2동    구내전입-전출  -169  -124   -47   311     59   177    431   556   107
180    명일2동    구간전입-전출    38    50   -96   -98     -8   -35   -280  -168   -59
181    명일2동  시/도간전입-전출    71  -175   -49   -68   -213  -307   -319  -613  -324

[182 rows x 11 columns]

In [97]:
un_hip = un_hip.dropna()
changes_un_hip = un_hip[un_hip['구분'].str.contains(r'(총전입-전출|구내전입-전출|구간전입-전출|시/도간전입-전출)')]
changes_un_hip

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
9,상도1동,총전입-전출,-390,-421,-361,3159,3404,579,-247,-811,-209
10,상도1동,구내전입-전출,-64,-156,-112,365,564,181,333,-294,38
11,상도1동,구간전입-전출,-551,-235,-305,2231,2006,118,-480,-634,-426
12,상도1동,시/도간전입-전출,225,-30,56,563,834,280,-100,117,179
22,상도2동,총전입-전출,106,42,-757,-319,-345,-401,-1234,2732,-335
23,상도2동,구내전입-전출,295,148,-188,-235,-241,34,-336,1274,4
24,상도2동,구간전입-전출,-72,165,-194,142,-104,-116,-496,1493,-119
25,상도2동,시/도간전입-전출,-117,-271,-375,-226,0,-319,-402,-35,-220
35,상도3동,총전입-전출,279,-189,-126,-268,12,-77,-60,392,221
36,상도3동,구내전입-전출,313,217,234,138,219,241,395,158,331
37,상도3동,구간전입-전출,83,53,-7,-96,108,-68,-48,476,161
38,상도3동,시/도간전입-전출,-117,-459,-353,-310,-315,-250,-407,-242,-271
48,상도4동,총전입-전출,-266,-150,-395,-278,-325,-110,-118,166,-236
49,상도4동,구내전입-전출,171,300,242,133,226,280,238,150,251
50,상도4동,구간전입-전출,-133,-2,-67,-12,-26,-26,144,431,-44
51,상도4동,시/도간전입-전출,-304,-448,-570,-399,-525,-364,-500,-415,-443
61,상계1동,총전입-전출,518,2313,-366,-437,-412,-738,-495,-625,-742
62,상계1동,구내전입-전출,734,1577,216,530,467,195,332,355,476
63,상계1동,구간전입-전출,59,770,3,-151,-227,-185,39,-8,-274
64,상계1동,시/도간전입-전출,-275,-34,-585,-816,-652,-748,-866,-972,-944
74,상계2동,총전입-전출,-333,281,-216,-490,-84,-125,-251,-98,-225
75,상계2동,구내전입-전출,230,490,353,100,287,261,214,382,422
76,상계2동,구간전입-전출,-212,-46,-255,-191,-152,-125,-154,-159,-323
77,상계2동,시/도간전입-전출,-351,-163,-314,-399,-219,-261,-311,-321,-324
87,상계5동,총전입-전출,-387,-461,-349,-308,-358,-397,-300,-352,-665
88,상계5동,구내전입-전출,40,-60,213,274,118,131,282,252,332
89,상계5동,구간전입-전출,-123,-19,-172,-103,-77,-232,59,-141,-323
90,상계5동,시/도간전입-전출,-304,-382,-390,-479,-399,-296,-641,-463,-674
100,상계8동,총전입-전출,-671,-69,-657,-536,-1226,-955,-662,-847,-869
101,상계8동,구내전입-전출,-146,-189,-331,-366,-468,-402,-139,-243,-118
102,상계8동,구간전입-전출,1,633,214,305,179,158,290,234,85
103,상계8동,시/도간전입-전출,-526,-513,-540,-475,-937,-711,-813,-838,-836
113,상계9동,총전입-전출,-703,-547,-401,-547,-444,-563,-485,-679,-526
114,상계9동,구내전입-전출,20,-78,16,-62,-43,-53,-113,-36,112
115,상계9동,구간전입-전출,-220,-34,5,-34,19,-118,90,-17,-120
116,상계9동,시/도간전입-전출,-503,-435,-422,-451,-420,-392,-462,-626,-518
126,상계10동,총전입-전출,-474,-538,-356,-385,-568,-598,-495,-688,-1820
127,상계10동,구내전입-전출,-15,-195,49,-17,-117,-186,-231,-294,-947
128,상계10동,구간전입-전출,-131,-51,-112,-18,-35,-119,98,59,-365
129,상계10동,시/도간전입-전출,-328,-292,-293,-350,-416,-293,-362,-453,-508
139,상계3.4동,총전입-전출,-717,-1359,-1081,-994,-911,-1097,-718,-1728,-2319
140,상계3.4동,구내전입-전출,-40,-309,128,-90,116,-273,32,-651,-866
141,상계3.4동,구간전입-전출,-205,-280,-336,-182,-226,-161,29,-307,-662
142,상계3.4동,시/도간전입-전출,-472,-770,-873,-722,-801,-663,-779,-770,-791
152,상계6.7동,총전입-전출,-712,-629,-710,-626,-648,-636,-787,496,-665
153,상계6.7동,구내전입-전출,-270,-273,-291,-115,-345,-335,-70,567,161
154,상계6.7동,구간전입-전출,-226,65,-75,60,83,153,62,620,-141
155,상계6.7동,시/도간전입-전출,-216,-421,-344,-571,-386,-454,-779,-691,-685
165,명일1동,총전입-전출,-593,-422,-395,-336,-358,-525,-4760,-484,-499
166,명일1동,구내전입-전출,-757,-204,-324,274,-47,-26,-2452,352,-26
167,명일1동,구간전입-전출,212,-3,136,-206,-43,-128,-819,-106,-65
168,명일1동,시/도간전입-전출,-48,-215,-207,-404,-268,-371,-1489,-730,-408
178,명일2동,총전입-전출,-60,-249,-192,145,-162,-165,-168,-225,-276
179,명일2동,구내전입-전출,-169,-124,-47,311,59,177,431,556,107
180,명일2동,구간전입-전출,38,50,-96,-98,-8,-35,-280,-168,-59
181,명일2동,시/도간전입-전출,71,-175,-49,-68,-213,-307,-319,-613,-324

In [98]:
temp

{'지역': '지역',
 '구분': '평균',
 2009: -116.14,
 2010: -255.61,
 2011: -251.24,
 2012: -230.84,
 2013: -223.94,
 2014: -195.61,
 2015: -305.01,
 2016: -311.68,
 2017: -218.86}

# 비율로 확인하기

In [181]:
df_popu = pd.read_csv('data/seoul_population.csv')
df_popu.head()

,Unnamed: 0,2008년12월_총인구수,2009년12월_총인구수,2010년12월_총인구수,2011년12월_총인구수,2012년12월_총인구수,2013년12월_총인구수,2014년12월_총인구수,2015년12월_총인구수,2016년12월_총인구수,2017년12월_총인구수,행정구역
0,1,1067.0,1095.0,1257.0,1301.0,1357.0,1339.0,1278.0,1248.0,1931.0,2022.0,서울특별시 중구 소공동(1114052000)
1,2,4496.0,4429.0,5537.0,5676.0,5892.0,5892.0,5795.0,5594.0,5481.0,5331.0,서울특별시 중구 회현동(1114054000)
2,3,2801.0,2892.0,3445.0,3411.0,3392.0,3279.0,3088.0,3010.0,3007.0,2942.0,서울특별시 중구 명동(1114055000)
3,4,4636.0,4551.0,4675.0,4616.0,4573.0,4484.0,4418.0,4300.0,4210.0,4078.0,서울특별시 중구 필동(1114057000)
4,5,5793.0,5742.0,5675.0,5596.0,5583.0,5551.0,5314.0,5175.0,4970.0,4782.0,서울특별시 중구 장충동(1114058000)

In [182]:
df_popu = df_popu.drop('Unnamed: 0', axis=1)
df_popu.columns

Index(['2008년12월_총인구수', '2009년12월_총인구수', '2010년12월_총인구수', '2011년12월_총인구수',
       '2012년12월_총인구수', '2013년12월_총인구수', '2014년12월_총인구수', '2015년12월_총인구수',
       '2016년12월_총인구수', '2017년12월_총인구수', '행정구역'],
      dtype='object')

In [183]:
df_popu = df_popu[['행정구역', '2008년12월_총인구수', '2009년12월_총인구수', '2010년12월_총인구수', '2011년12월_총인구수',
                   '2012년12월_총인구수', '2013년12월_총인구수', '2014년12월_총인구수', '2015년12월_총인구수',
                   '2016년12월_총인구수', '2017년12월_총인구수']]
df_popu.head()

,행정구역,2008년12월_총인구수,2009년12월_총인구수,2010년12월_총인구수,2011년12월_총인구수,2012년12월_총인구수,2013년12월_총인구수,2014년12월_총인구수,2015년12월_총인구수,2016년12월_총인구수,2017년12월_총인구수
0,서울특별시 중구 소공동(1114052000),1067.0,1095.0,1257.0,1301.0,1357.0,1339.0,1278.0,1248.0,1931.0,2022.0
1,서울특별시 중구 회현동(1114054000),4496.0,4429.0,5537.0,5676.0,5892.0,5892.0,5795.0,5594.0,5481.0,5331.0
2,서울특별시 중구 명동(1114055000),2801.0,2892.0,3445.0,3411.0,3392.0,3279.0,3088.0,3010.0,3007.0,2942.0
3,서울특별시 중구 필동(1114057000),4636.0,4551.0,4675.0,4616.0,4573.0,4484.0,4418.0,4300.0,4210.0,4078.0
4,서울특별시 중구 장충동(1114058000),5793.0,5742.0,5675.0,5596.0,5583.0,5551.0,5314.0,5175.0,4970.0,4782.0

In [184]:
org_cols = ['2008년12월_총인구수', '2009년12월_총인구수', '2010년12월_총인구수', '2011년12월_총인구수',
            '2012년12월_총인구수', '2013년12월_총인구수', '2014년12월_총인구수', '2015년12월_총인구수',
            '2016년12월_총인구수', '2017년12월_총인구수']
new_cols = [year for year in range(2008, 2018)]
cols = dict()
for o, n in zip(org_cols, new_cols):
    cols[o] = n
df_popu = df_popu.rename(columns=cols)
df_popu.head()

,행정구역,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,서울특별시 중구 소공동(1114052000),1067.0,1095.0,1257.0,1301.0,1357.0,1339.0,1278.0,1248.0,1931.0,2022.0
1,서울특별시 중구 회현동(1114054000),4496.0,4429.0,5537.0,5676.0,5892.0,5892.0,5795.0,5594.0,5481.0,5331.0
2,서울특별시 중구 명동(1114055000),2801.0,2892.0,3445.0,3411.0,3392.0,3279.0,3088.0,3010.0,3007.0,2942.0
3,서울특별시 중구 필동(1114057000),4636.0,4551.0,4675.0,4616.0,4573.0,4484.0,4418.0,4300.0,4210.0,4078.0
4,서울특별시 중구 장충동(1114058000),5793.0,5742.0,5675.0,5596.0,5583.0,5551.0,5314.0,5175.0,4970.0,4782.0

In [185]:
df_popu = df_popu.drop(2008, axis=1)
df_popu.head()

,행정구역,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,서울특별시 중구 소공동(1114052000),1095.0,1257.0,1301.0,1357.0,1339.0,1278.0,1248.0,1931.0,2022.0
1,서울특별시 중구 회현동(1114054000),4429.0,5537.0,5676.0,5892.0,5892.0,5795.0,5594.0,5481.0,5331.0
2,서울특별시 중구 명동(1114055000),2892.0,3445.0,3411.0,3392.0,3279.0,3088.0,3010.0,3007.0,2942.0
3,서울특별시 중구 필동(1114057000),4551.0,4675.0,4616.0,4573.0,4484.0,4418.0,4300.0,4210.0,4078.0
4,서울특별시 중구 장충동(1114058000),5742.0,5675.0,5596.0,5583.0,5551.0,5314.0,5175.0,4970.0,4782.0

In [186]:
df_popu['자치구'] = df_popu['행정구역'].str.extractall(r'서울특별시\s(\w+구)\s[\w\d\.]+동\(\d+\)$').values
df_popu['동'] = df_popu['행정구역'].str.extractall(r'서울특별시\s\w+구\s([\w\d\.]+동)\(\d+\)$').values
df_popu = df_popu.drop('행정구역', axis=1)

In [187]:
df_popu = df_popu[['자치구','동', 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]]
df_popu.head()

,자치구,동,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,중구,소공동,1095.0,1257.0,1301.0,1357.0,1339.0,1278.0,1248.0,1931.0,2022.0
1,중구,회현동,4429.0,5537.0,5676.0,5892.0,5892.0,5795.0,5594.0,5481.0,5331.0
2,중구,명동,2892.0,3445.0,3411.0,3392.0,3279.0,3088.0,3010.0,3007.0,2942.0
3,중구,필동,4551.0,4675.0,4616.0,4573.0,4484.0,4418.0,4300.0,4210.0,4078.0
4,중구,장충동,5742.0,5675.0,5596.0,5583.0,5551.0,5314.0,5175.0,4970.0,4782.0

In [113]:
df_move = pd.read_csv('data/seoul_in_out_total_abs.csv')
df_move.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597

In [151]:
df_move_inner = df_move['기간,동,구내전입,구내전출,구간전입,구간전출'.split(',')]
df_move_inner.head()

     기간    동    구내전입    구내전출    구간전입    구간전출
0  2009   합계  560864  560864  725991  725991
1  2009   소계    5921    5921   15157   18036
2  2009  사직동     448     402    1087    1160
3  2009  삼청동     137     191     317     402
4  2009  부암동     477     483     945    1100

In [212]:
years = [year for year in range(2009, 2018)]
popu_sums = list(df_popu.iloc[:,2:].sum())
year_sum = dict()
for y, s in zip(years, popu_sums):
    year_sum[y] = s
year_sum

{2009: 9970982.0,
 2010: 10068466.0,
 2011: 10011009.0,
 2012: 9956693.0,
 2013: 9906796.0,
 2014: 9872478.0,
 2015: 9796248.0,
 2016: 9710502.0,
 2017: 9642532.0}

In [198]:
df_2009.iloc[0,6] = popu_sums[0]
df_2009.head()

     기간    동    구내전입    구내전출    구간전입    구간전출         인구
0  2009   합계  560864  560864  725991  725991  9970982.0
1  2009   소계    5921    5921   15157   18036        NaN
2  2009  사직동     448     402    1087    1160    10029.0
3  2009  삼청동     137     191     317     402     3548.0
4  2009  부암동     477     483     945    1100    11330.0

In [210]:
year=2009
df_popu[['동', year]].head()

     동    2009
0  소공동  1095.0
1  회현동  4429.0
2   명동  2892.0
3   필동  4551.0
4  장충동  5742.0

In [211]:
result = pd.DataFrame(columns='기간,동,구내전입,구내전출,구간전입,구간전출,인구'.split(','))
result

Empty DataFrame
Columns: [기간, 동, 구내전입, 구내전출, 구간전입, 구간전출, 인구]
Index: []

In [215]:
result = pd.DataFrame(columns='기간,동,구내전입,구내전출,구간전입,구간전출,인구'.split(','))

for year in range(2009, 2018):
    df = df_move_inner[df_move_inner['기간'] == year]
    df = df.merge(df_popu[['동', year]], how='left').rename(columns={year:'인구'})
    df.iloc[0,6] = year_sum[year]
    result = result.append(df)

result.head()

     기간    동    구내전입    구내전출    구간전입    구간전출         인구
0  2009   합계  560864  560864  725991  725991  9970982.0
1  2009   소계    5921    5921   15157   18036        NaN
2  2009  사직동     448     402    1087    1160    10029.0
3  2009  삼청동     137     191     317     402     3548.0
4  2009  부암동     477     483     945    1100    11330.0

In [224]:
result[result['동'].str.contains(r'(합계|총계)')]

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

     기간   동    구내전입    구내전출    구간전입    구간전출          인구
0  2009  합계  560864  560864  725991  725991   9970982.0
0  2010  합계  520345  520345  679363  679363  10068466.0
0  2011  합계  543807  543807  671315  671315  10011009.0
0  2012  총계  473458  473458  595842  595842   9956693.0
0  2013  합계  468394  468394  584614  584614   9906796.0
0  2014  합계  495401  495401  602622  602622   9872478.0
0  2015  합계  524267  524267  605262  605262   9796248.0
0  2016  합계  487722  487722  574193  574193   9710502.0
0  2017  합계  454536  454536  564271  564271   9642532.0

In [225]:
result.isnull().sum()

기간         0
동          0
구내전입       0
구내전출       0
구간전입       0
구간전출       0
인구      1982
dtype: int64

In [234]:
temp_cols = '구내전입,구내전출,구간전입,구간전출'.split(',')
for col in temp_cols:
    result[f'{col}비율'] = result[col].values/(result['인구'].values * 10)
result.head()

,기간,동,구내전입,구내전출,구간전입,구간전출,인구,구내전입비율,구내전출비율,구간전입비율,구간전출비율
0,2009,합계,560864,560864,725991,725991,9970982.0,0.00562496,0.00562496,0.00728104,0.00728104
1,2009,소계,5921,5921,15157,18036,NaN,NaN,NaN,NaN,NaN
2,2009,사직동,448,402,1087,1160,10029.0,0.00446705,0.00400838,0.0108386,0.0115665
3,2009,삼청동,137,191,317,402,3548.0,0.00386133,0.00538331,0.00893461,0.0113303
4,2009,부암동,477,483,945,1100,11330.0,0.00421006,0.00426302,0.00834069,0.00970874

In [230]:
result['구내전입'].values / result['인구'].values

array([0.05624962516229595, nan, 0.044670455678532256, ..., nan, nan,
       0.06985521717423865], dtype=object)

In [239]:
df = pd.read_csv('C:/Users/rlath/dataitgirls/Next_Hip_Place/code/seoul_populations/data/2010_household.csv', encoding='euc-kr')
df.head()

,기간,자치구,동,일반가구,일반가구.1,일반가구.2,일반가구.3,일반가구.4,일반가구.5,일반가구.6
0,기간,자치구,동,계,1인가구,2인가구,3인가구,4인가구,5인가구,6인이상가구
1,2010,합계,합계,"3,504,297","854,606","781,527","788,115","807,836","209,061","63,152"
2,2010,종로구,소계,"57,807","18,156","13,073","11,255","10,832","3,315","1,176"
3,2010,종로구,사직동,"3,442","1,033",865,720,585,180,59
4,2010,종로구,삼청동,"1,048",271,263,219,168,86,41

In [246]:
df[df['기간'] == 2015]

Empty DataFrame
Columns: [기간, 자치구, 동, 일반가구, 일반가구.1, 일반가구.2, 일반가구.3, 일반가구.4, 일반가구.5, 일반가구.6]
Index: []