In [263]:
import pandas as pd
import numpy as np
import re

In [308]:
cols = {'구분' : '총전입'}
values = '총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출'.split(',')
for i in range(1,8):
    cols[f'구분.{i}'] = values[i-1]
cols

{'구분': '총전입',
 '구분.1': '총전출',
 '구분.2': '구내전입',
 '구분.3': '구내전출',
 '구분.4': '구간전입',
 '구분.5': '구간전출',
 '구분.6': '시/도간전입',
 '구분.7': '시/도간전출'}

In [330]:
def cleaning_df(year):
    df = pd.read_csv(f'data/data_org/seoul_in_out_{year}_org.csv')
    df = df.drop(0).drop(1)
    print(year)
    print(df.shape)
    print(df.columns)
    df = df.rename(columns=cols)
#     정리된거 저장도 같이 해두자
    df = df.apply(lambda x: x.str.replace(',', ''))
    print(df.iloc[:3,:])
    df.to_csv(f'data/seoul_in_out_{year}.csv', index=False)
    
    return df

In [331]:
def concat_dfs(year, result):
    df = cleaning_df(year)
    result = result.append(df, ignore_index=True)
    return result

In [332]:
result = pd.DataFrame(columns=['기간', '자치구', '동', '총전입', '총전출', '구내전입',\
                               '구내전출', '구간전입', '구간전출','시/도간전입', '시/도간전출'])
result.head()

Empty DataFrame
Columns: [기간, 자치구, 동, 총전입, 총전출, 구내전입, 구내전출, 구간전입, 구간전출, 시/도간전입, 시/도간전출]
Index: []

In [333]:
for year in range(2009, 2018):
    result = concat_dfs(year, result)
result.shape

2009
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2009   합계   합계  1873188  1925452  560864  560864  725991  725991  586333
3  2009  종로구   소계    31031    33661    5921    5921   15157   18036    9953
4  2009  종로구  사직동     2140     2076     448     402    1087    1160     605

   시/도간전출
2  638597
3    9704
4     514
2010
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2010   합계   합계  1733015  1848038  520345  520345  679363  679363  533307
3  2010  종로구   소계    29208    32928    5703    5703   14256   17822    9249
4  2010  종로구  사직동     2041     2261     433     445    1017    1209     591

   시/도간전출
2  648330
3    9403
4     607
2011
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2011   합계   합계  1721748  1834806  543807  543807  671315  671315  506626
3  2011  종로구   소계    28329    30663    5551    5551   14089   16214    8689
4  2011  종로구  사직동     2115     2215     467     487    1047    1133     601

   시/도간전출
2  619684
3    8898
4     595
2012
(449, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2012   총계   총계  1555281  1658928  473458  473458  595842  595842  485981
3  2012  종로구   소계    26001    29398    4935    4935   12530   15681    8536
4  2012  종로구  사직동     1811     1979     415     417     924     997     472

   시/도간전출
2  589628
3    8782
4     565
2013
(449, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2013   합계   합계  1520090  1620640  468394  468394  584614  584614  467082
3  2013  종로구   소계    24676    30007    4921    4921   11803   16405    7952
4  2013  종로구  사직동     1665     1872     406     360     828     990     431

   시/도간전출
2  567632
3    8681
4     522
2014
(449, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2014   합계   합계  1573594  1661425  495401  495401  602622  602622  475571
3  2014  종로구   소계    24191    27484    4507    4507   11243   14657    8441
4  2014  종로구  사직동     1694     1840     377     360     833    1003     484

   시/도간전출
2  563402
3    8320
4     477
2015
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2015   합계   합계  1589431  1726687  524267  524267  605262  605262  459902
3  2015  종로구   소계    24951    27470    4617    4617   11846   14426    8488
4  2015  종로구  사직동     1708     1840     294     364     967    1030     447

   시/도간전출
2  597158
3    8427
4     446
2016
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2016   합계   합계  1515602  1655859  487722  487722  574193  574193  453687
3  2016  종로구   소계    23604    26386    4145    4145   11135   13913    8324
4  2016  종로구  사직동     1725     1790     290     301     928     988     507

   시/도간전출
2  593944
3    8328
4     501
2017
(450, 11)
Index(['기간', '자치구', '동', '구분', '구분.1', '구분.2', '구분.3', '구분.4', '구분.5', '구분.6',
       '구분.7'],
      dtype='object')
     기간  자치구    동      총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  \
2  2017   합계   합계  1472937  1571423  454536  454536  564271  564271  454130
3  2017  종로구   소계    28020    25814    4512    4512   14610   13178    8898
4  2017  종로구  사직동     1733     1993     315     517     899     993     519

   시/도간전출
2  552616
3    8124
4     483

(4047, 11)

# 여기서부터 돌리기

In [334]:
import pandas as pd
import numpy as np
import re

In [335]:
result = pd.DataFrame(columns=['기간', '자치구', '동', '총전입', '총전출', '구내전입',\
                               '구내전출', '구간전입', '구간전출','시/도간전입', '시/도간전출'])
result.head()

Empty DataFrame
Columns: [기간, 자치구, 동, 총전입, 총전출, 구내전입, 구내전출, 구간전입, 구간전출, 시/도간전입, 시/도간전출]
Index: []

In [337]:
for year in range(2009, 2018):
    df = pd.read_csv(f'data/seoul_in_out_{year}.csv')
    result = result.append(df, ignore_index=True)
result.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597

In [338]:
result.shape

(4047, 11)

In [339]:
result.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597

In [220]:
result.to_csv('seoul_in_out_total_abs.csv', index=False)

In [341]:
diff_values = result.copy(deep=True)
diff_values = diff_values.iloc[:, 3:]
diff_values.head()

       총전입      총전출    구내전입    구내전출    구간전입    구간전출  시/도간전입  시/도간전출
0  1873188  1925452  560864  560864  725991  725991  586333  638597
1    31031    33661    5921    5921   15157   18036    9953    9704
2     2140     2076     448     402    1087    1160     605     514
3      694      808     137     191     317     402     240     215
4     1925     2180     477     483     945    1100     503     597

In [342]:
new_cols = '총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출'.split(',')
for i in range(len(new_cols)):
    diff_values[new_cols[i]] = diff_values.iloc[:,i*2].values - diff_values.iloc[:,i*2+1].values
diff_values.head()

,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
0,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264
1,31031,33661,5921,5921,15157,18036,9953,9704,-2630,0,-2879,249
2,2140,2076,448,402,1087,1160,605,514,64,46,-73,91
3,694,808,137,191,317,402,240,215,-114,-54,-85,25
4,1925,2180,477,483,945,1100,503,597,-255,-6,-155,-94

In [343]:
diff_values[['기간', '자치구', '동']] = result.iloc[:,:3].copy(deep=True)
diff_values.head()

,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출,기간,자치구,동
0,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264,2009,합계,합계
1,31031,33661,5921,5921,15157,18036,9953,9704,-2630,0,-2879,249,2009,종로구,소계
2,2140,2076,448,402,1087,1160,605,514,64,46,-73,91,2009,종로구,사직동
3,694,808,137,191,317,402,240,215,-114,-54,-85,25,2009,종로구,삼청동
4,1925,2180,477,483,945,1100,503,597,-255,-6,-155,-94,2009,종로구,부암동

In [344]:
diff_values = diff_values[['기간', '자치구', '동', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출',\
                  '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']]
diff_values.head()

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264
1,2009,종로구,소계,31031,33661,5921,5921,15157,18036,9953,9704,-2630,0,-2879,249
2,2009,종로구,사직동,2140,2076,448,402,1087,1160,605,514,64,46,-73,91
3,2009,종로구,삼청동,694,808,137,191,317,402,240,215,-114,-54,-85,25
4,2009,종로구,부암동,1925,2180,477,483,945,1100,503,597,-255,-6,-155,-94

In [345]:
diff_values.shape

(4047, 15)

In [346]:
diff_values.to_csv('seoul_in_out_total_diffs.csv', index=False)

# 분류별로 확인하기

In [258]:
'''
현핫플 : 연남동, 익선동, 성수동, 샤로수길(봉천동), 망원동, 사직동
기핫플 : 신사동, 삼청동, 명동
비핫플 : 상도동, 목동, 신정동, 상계동, 명일동
'''

'\n현핫플 : 연남동, 익선동, 성수동, 샤로수길(봉천동), 망원동\n기핫플 : 신사동, 삼청동, 명동\n비핫플 : 상도동, 목동, 신정동, 상계동\n'

In [350]:
diff_values[diff_values['동'] == '연남동']

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
230,2009,마포구,연남동,4149,4369,1154,1301,1688,1716,1307,1352,-220,-147,-28,-45
680,2010,마포구,연남동,3878,4344,1088,1298,1645,1701,1145,1345,-466,-210,-56,-200
1130,2011,마포구,연남동,3748,4123,1113,1229,1501,1644,1134,1250,-375,-116,-143,-116
1579,2012,마포구,연남동,3672,3956,1093,1102,1385,1619,1194,1235,-284,-9,-234,-41
2028,2013,마포구,연남동,3516,3617,993,902,1441,1497,1082,1218,-101,91,-56,-136
2477,2014,마포구,연남동,3343,3898,919,1094,1252,1516,1172,1288,-555,-175,-264,-116
2926,2015,마포구,연남동,3284,3999,905,1036,1307,1767,1072,1196,-715,-131,-460,-124
3376,2016,마포구,연남동,3173,3809,829,922,1141,1754,1203,1133,-636,-93,-613,70
3826,2017,마포구,연남동,2976,3773,742,922,1078,1619,1156,1232,-797,-180,-541,-76

In [364]:
diff_values.columns

Index(['기간', '자치구', '동', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출',
       '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출'],
      dtype='object')

In [457]:
hots = '연남동, 종로1.2.3.4가동, 종로5·6가동, 성수1가2동, 낙성대동, 망원1동, 망원2동, 사직동'.split(', ')
hots

['연남동', '종로1.2.3.4가동', '종로5·6가동', '성수1가2동', '낙성대동', '망원1동', '망원2동', '사직동']

In [470]:
len(hots)

8

In [424]:
hot = '연남동'
diff_values[diff_values['동'] == hot].set_index('기간').T

기간         2009  2010  2011  2012  2013  2014  2015  2016  2017
자치구         마포구   마포구   마포구   마포구   마포구   마포구   마포구   마포구   마포구
동           연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동
총전입        4149  3878  3748  3672  3516  3343  3284  3173  2976
총전출        4369  4344  4123  3956  3617  3898  3999  3809  3773
구내전입       1154  1088  1113  1093   993   919   905   829   742
구내전출       1301  1298  1229  1102   902  1094  1036   922   922
구간전입       1688  1645  1501  1385  1441  1252  1307  1141  1078
구간전출       1716  1701  1644  1619  1497  1516  1767  1754  1619
시/도간전입     1307  1145  1134  1194  1082  1172  1072  1203  1156
시/도간전출     1352  1345  1250  1235  1218  1288  1196  1133  1232
총전입-전출     -220  -466  -375  -284  -101  -555  -715  -636  -797
구내전입-전출    -147  -210  -116    -9    91  -175  -131   -93  -180
구간전입-전출     -28   -56  -143  -234   -56  -264  -460  -613  -541
시/도간전입-전출   -45  -200  -116   -41  -136  -116  -124    70   -76

In [471]:
now_hot = pd.DataFrame(columns=[year for year in range(2009, 2018)])

for hot in hots:
    df = diff_values[diff_values['동'] == hot].set_index('기간').T.iloc[1:, :]
#     print(df.head())
    now_hot = now_hot.append(df, ignore_index = True)
now_hot.head()

기간  2009  2010  2011  2012  2013  2014  2015  2016  2017
0    연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동
1   4149  3878  3748  3672  3516  3343  3284  3173  2976
2   4369  4344  4123  3956  3617  3898  3999  3809  3773
3   1154  1088  1113  1093   993   919   905   829   742
4   1301  1298  1229  1102   902  1094  1036   922   922

In [472]:
now_hot['지역'] = np.nan
for i in range(len(hots)):
    index = i*13
    for n in range(1, 13):
        now_hot['지역'][index+n] = now_hot.iloc[index,0]
now_hot.head()

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\rlath\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

기간  2009  2010  2011  2012  2013  2014  2015  2016  2017   지역
0    연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동  NaN
1   4149  3878  3748  3672  3516  3343  3284  3173  2976  연남동
2   4369  4344  4123  3956  3617  3898  3999  3809  3773  연남동
3   1154  1088  1113  1093   993   919   905   829   742  연남동
4   1301  1298  1229  1102   902  1094  1036   922   922  연남동

In [483]:
now_hot.head(13)

기간  2009  2010  2011  2012  2013  2014  2015  2016  2017   지역
0    연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동   연남동  NaN
1   4149  3878  3748  3672  3516  3343  3284  3173  2976  연남동
2   4369  4344  4123  3956  3617  3898  3999  3809  3773  연남동
3   1154  1088  1113  1093   993   919   905   829   742  연남동
4   1301  1298  1229  1102   902  1094  1036   922   922  연남동
5   1688  1645  1501  1385  1441  1252  1307  1141  1078  연남동
6   1716  1701  1644  1619  1497  1516  1767  1754  1619  연남동
7   1307  1145  1134  1194  1082  1172  1072  1203  1156  연남동
8   1352  1345  1250  1235  1218  1288  1196  1133  1232  연남동
9   -220  -466  -375  -284  -101  -555  -715  -636  -797  연남동
10  -147  -210  -116    -9    91  -175  -131   -93  -180  연남동
11   -28   -56  -143  -234   -56  -264  -460  -613  -541  연남동
12   -45  -200  -116   -41  -136  -116  -124    70   -76  연남동

In [484]:
len(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출'])

13

In [485]:
len(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']*len(hots))

104

In [466]:
diff_values.columns

Index(['기간', '자치구', '동', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출',
       '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출'],
      dtype='object')

In [486]:
now_hot['구분'] = list(['지역', '총전입', '총전출', '구내전입', '구내전출', '구간전입', '구간전출', '시/도간전입', '시/도간전출', '총전입-전출', '구내전입-전출', '구간전입-전출', '시/도간전입-전출']*len(hots))

In [487]:
now_hot = now_hot[['지역', '구분', 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]]
now_hot

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,NaN,지역,연남동,연남동,연남동,연남동,연남동,연남동,연남동,연남동,연남동
1,연남동,총전입,4149,3878,3748,3672,3516,3343,3284,3173,2976
2,연남동,총전출,4369,4344,4123,3956,3617,3898,3999,3809,3773
3,연남동,구내전입,1154,1088,1113,1093,993,919,905,829,742
4,연남동,구내전출,1301,1298,1229,1102,902,1094,1036,922,922
5,연남동,구간전입,1688,1645,1501,1385,1441,1252,1307,1141,1078
6,연남동,구간전출,1716,1701,1644,1619,1497,1516,1767,1754,1619
7,연남동,시/도간전입,1307,1145,1134,1194,1082,1172,1072,1203,1156
8,연남동,시/도간전출,1352,1345,1250,1235,1218,1288,1196,1133,1232
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
13,NaN,지역,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동,종로1.2.3.4가동
14,종로1.2.3.4가동,총전입,1880,1815,1814,1732,1686,1951,1872,1757,1690
15,종로1.2.3.4가동,총전출,1882,1876,1855,1677,1756,1892,1922,1909,1774
16,종로1.2.3.4가동,구내전입,199,229,189,180,183,190,184,128,136
17,종로1.2.3.4가동,구내전출,218,212,228,231,218,224,287,250,264
18,종로1.2.3.4가동,구간전입,950,889,950,844,839,808,821,856,757
19,종로1.2.3.4가동,구간전출,1016,1014,1003,891,926,996,960,974,870
20,종로1.2.3.4가동,시/도간전입,731,697,675,708,664,953,867,773,797
21,종로1.2.3.4가동,시/도간전출,648,650,624,555,612,672,675,685,640
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
26,NaN,지역,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동,종로5·6가동
27,종로5·6가동,총전입,1105,1126,965,1038,892,870,1129,920,989
28,종로5·6가동,총전출,1290,1276,1107,1055,1069,1032,1142,1137,1093
29,종로5·6가동,구내전입,235,235,194,225,203,155,175,163,174
...,...,...,...,...,...,...,...,...,...,...,...
74,망원1동,총전입-전출,-288,-362,-475,-422,-411,-952,-938,-539,-494
75,망원1동,구내전입-전출,121,-81,52,160,233,-293,-97,126,38
76,망원1동,구간전입-전출,-144,35,-168,-203,-172,-392,-424,-395,-291
77,망원1동,시/도간전입-전출,-265,-316,-359,-379,-472,-267,-417,-270,-241
78,NaN,지역,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동,망원2동
79,망원2동,총전입,3974,3556,3314,2922,2997,3155,3099,2978,2424
80,망원2동,총전출,3673,4108,3631,3426,3406,3302,3513,3388,2952
81,망원2동,구내전입,1692,1472,1401,1291,1322,1482,1464,1426,1009
82,망원2동,구내전출,1305,1412,1199,1076,1177,1153,1194,1124,979
83,망원2동,구간전입,1313,1141,1071,832,967,903,885,793,741
84,망원2동,구간전출,1291,1308,1231,1127,1164,1057,1243,1181,981
85,망원2동,시/도간전입,969,943,842,799,708,770,750,759,674
86,망원2동,시/도간전출,1077,1388,1201,1223,1065,1092,1076,1083,992
87,망원2동,총전입-전출,301,-552,-317,-504,-409,-147,-414,-410,-528
88,망원2동,구내전입-전출,387,60,202,215,145,329,270,302,30
89,망원2동,구간전입-전출,22,-167,-160,-295,-197,-154,-358,-388,-240
90,망원2동,시/도간전입-전출,-108,-445,-359,-424,-357,-322,-326,-324,-318
91,NaN,지역,사직동,사직동,사직동,사직동,사직동,사직동,사직동,사직동,사직동
92,사직동,총전입,2140,2041,2115,1811,1665,1694,1708,1725,1733
93,사직동,총전출,2076,2261,2215,1979,1872,1840,1840,1790,1993
94,사직동,구내전입,448,433,467,415,406,377,294,290,315
95,사직동,구내전출,402,445,487,417,360,360,364,301,517
96,사직동,구간전입,1087,1017,1047,924,828,833,967,928,899
97,사직동,구간전출,1160,1209,1133,997,990,1003,1030,988,993
98,사직동,시/도간전입,605,591,601,472,431,484,447,507,519
99,사직동,시/도간전출,514,607,595,565,522,477,446,501,483
100,사직동,총전입-전출,64,-220,-100,-168,-207,-146,-132,-65,-260
101,사직동,구내전입-전출,46,-12,-20,-2,46,17,-70,-11,-202
102,사직동,구간전입-전출,-73,-192,-86,-73,-162,-170,-63,-60,-94
103,사직동,시/도간전입-전출,91,-16,6,-93,-91,7,1,6,36

In [488]:
now_hot = now_hot.dropna()

In [489]:
now_hot.head(30)

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
1,연남동,총전입,4149,3878,3748,3672,3516,3343,3284,3173,2976
2,연남동,총전출,4369,4344,4123,3956,3617,3898,3999,3809,3773
3,연남동,구내전입,1154,1088,1113,1093,993,919,905,829,742
4,연남동,구내전출,1301,1298,1229,1102,902,1094,1036,922,922
5,연남동,구간전입,1688,1645,1501,1385,1441,1252,1307,1141,1078
6,연남동,구간전출,1716,1701,1644,1619,1497,1516,1767,1754,1619
7,연남동,시/도간전입,1307,1145,1134,1194,1082,1172,1072,1203,1156
8,연남동,시/도간전출,1352,1345,1250,1235,1218,1288,1196,1133,1232
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
14,종로1.2.3.4가동,총전입,1880,1815,1814,1732,1686,1951,1872,1757,1690
15,종로1.2.3.4가동,총전출,1882,1876,1855,1677,1756,1892,1922,1909,1774
16,종로1.2.3.4가동,구내전입,199,229,189,180,183,190,184,128,136
17,종로1.2.3.4가동,구내전출,218,212,228,231,218,224,287,250,264
18,종로1.2.3.4가동,구간전입,950,889,950,844,839,808,821,856,757
19,종로1.2.3.4가동,구간전출,1016,1014,1003,891,926,996,960,974,870
20,종로1.2.3.4가동,시/도간전입,731,697,675,708,664,953,867,773,797
21,종로1.2.3.4가동,시/도간전출,648,650,624,555,612,672,675,685,640
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
27,종로5·6가동,총전입,1105,1126,965,1038,892,870,1129,920,989
28,종로5·6가동,총전출,1290,1276,1107,1055,1069,1032,1142,1137,1093
29,종로5·6가동,구내전입,235,235,194,225,203,155,175,163,174
30,종로5·6가동,구내전출,300,291,208,204,258,212,272,281,219
31,종로5·6가동,구간전입,516,552,405,447,374,354,410,342,363
32,종로5·6가동,구간전출,605,659,565,511,519,487,492,493,516

In [490]:
now_hot[now_hot['구분'] == '총전입-전출']

기간            지역      구분  2009  2010  2011  2012  2013  2014  2015  2016  2017
9            연남동  총전입-전출  -220  -466  -375  -284  -101  -555  -715  -636  -797
22   종로1.2.3.4가동  총전입-전출    -2   -61   -41    55   -70    59   -50  -152   -84
35       종로5·6가동  총전입-전출  -185  -150  -142   -17  -177  -162   -13  -217  -104
48        성수1가2동  총전입-전출  -529  -465  -451  -310  -526  -596  -754  -590  -617
61          낙성대동  총전입-전출  -362  -117  -188  -137  -153  -269  -235  -179  -377
74          망원1동  총전입-전출  -288  -362  -475  -422  -411  -952  -938  -539  -494
87          망원2동  총전입-전출   301  -552  -317  -504  -409  -147  -414  -410  -528
100          사직동  총전입-전출    64  -220  -100  -168  -207  -146  -132   -65  -260

In [503]:
diff_values[diff_values['자치구'] == '합계']

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
0,2009,합계,합계,1873188,1925452,560864,560864,725991,725991,586333,638597,-52264,0,0,-52264
450,2010,합계,합계,1733015,1848038,520345,520345,679363,679363,533307,648330,-115023,0,0,-115023
900,2011,합계,합계,1721748,1834806,543807,543807,671315,671315,506626,619684,-113058,0,0,-113058
1799,2013,합계,합계,1520090,1620640,468394,468394,584614,584614,467082,567632,-100550,0,0,-100550
2248,2014,합계,합계,1573594,1661425,495401,495401,602622,602622,475571,563402,-87831,0,0,-87831
2697,2015,합계,합계,1589431,1726687,524267,524267,605262,605262,459902,597158,-137256,0,0,-137256
3147,2016,합계,합계,1515602,1655859,487722,487722,574193,574193,453687,593944,-140257,0,0,-140257
3597,2017,합계,합계,1472937,1571423,454536,454536,564271,564271,454130,552616,-98486,0,0,-98486

In [510]:
diff_values.tail(2)

,기간,자치구,동,총전입,총전출,구내전입,구내전출,구간전입,구간전출,시/도간전입,시/도간전출,총전입-전출,구내전입-전출,구간전입-전출,시/도간전입-전출
4045,2017,강동구,천호2동,6499,6025,2679,2328,2083,1492,1737,2205,474,351,591,-468
4046,2017,강동구,길동,7512,8644,3498,3430,1864,1881,2150,3333,-1132,68,-17,-1183

In [515]:
total_means = [np.round(-52264 / 450, 4),
np.round(-115023 / 450, 4),
np.round(-113058 / (1799-900), 4),
np.round(-100550 / (2248-1799), 4),
np.round(-87831 / (2697-2248), 4),
np.round(-137256 / (3147-2697), 4),
np.round(-140257 / (3597-3147), 4),
np.round(-98486 / (4046-3597), 4)]

In [514]:
changes_now_hot = now_hot[now_hot['구분'].str.contains(r'(총전입-전출|구내전입-전출|구간전입-전출|시/도간전입-전출)')]
changes_now_hot

C:\Users\rlath\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

기간,지역,구분,2009,2010,2011,2012,2013,2014,2015,2016,2017
9,연남동,총전입-전출,-220,-466,-375,-284,-101,-555,-715,-636,-797
10,연남동,구내전입-전출,-147,-210,-116,-9,91,-175,-131,-93,-180
11,연남동,구간전입-전출,-28,-56,-143,-234,-56,-264,-460,-613,-541
12,연남동,시/도간전입-전출,-45,-200,-116,-41,-136,-116,-124,70,-76
22,종로1.2.3.4가동,총전입-전출,-2,-61,-41,55,-70,59,-50,-152,-84
23,종로1.2.3.4가동,구내전입-전출,-19,17,-39,-51,-35,-34,-103,-122,-128
24,종로1.2.3.4가동,구간전입-전출,-66,-125,-53,-47,-87,-188,-139,-118,-113
25,종로1.2.3.4가동,시/도간전입-전출,83,47,51,153,52,281,192,88,157
35,종로5·6가동,총전입-전출,-185,-150,-142,-17,-177,-162,-13,-217,-104
36,종로5·6가동,구내전입-전출,-65,-56,-14,21,-55,-57,-97,-118,-45
37,종로5·6가동,구간전입-전출,-89,-107,-160,-64,-145,-133,-82,-151,-153
38,종로5·6가동,시/도간전입-전출,-31,13,32,26,23,28,166,52,94
48,성수1가2동,총전입-전출,-529,-465,-451,-310,-526,-596,-754,-590,-617
49,성수1가2동,구내전입-전출,-28,-4,-5,-27,44,-94,-228,-160,-229
50,성수1가2동,구간전입-전출,-303,-298,-370,-95,-321,-241,-280,-181,-285
51,성수1가2동,시/도간전입-전출,-198,-163,-76,-188,-249,-261,-246,-249,-103
61,낙성대동,총전입-전출,-362,-117,-188,-137,-153,-269,-235,-179,-377
62,낙성대동,구내전입-전출,-160,-107,-225,-213,-256,-155,-216,-242,-457
63,낙성대동,구간전입-전출,-510,-155,-235,-311,-208,-376,-186,-275,-333
64,낙성대동,시/도간전입-전출,308,145,272,387,311,262,167,338,413
74,망원1동,총전입-전출,-288,-362,-475,-422,-411,-952,-938,-539,-494
75,망원1동,구내전입-전출,121,-81,52,160,233,-293,-97,126,38
76,망원1동,구간전입-전출,-144,35,-168,-203,-172,-392,-424,-395,-291
77,망원1동,시/도간전입-전출,-265,-316,-359,-379,-472,-267,-417,-270,-241
87,망원2동,총전입-전출,301,-552,-317,-504,-409,-147,-414,-410,-528
88,망원2동,구내전입-전출,387,60,202,215,145,329,270,302,30
89,망원2동,구간전입-전출,22,-167,-160,-295,-197,-154,-358,-388,-240
90,망원2동,시/도간전입-전출,-108,-445,-359,-424,-357,-322,-326,-324,-318
100,사직동,총전입-전출,64,-220,-100,-168,-207,-146,-132,-65,-260
101,사직동,구내전입-전출,46,-12,-20,-2,46,17,-70,-11,-202
102,사직동,구간전입-전출,-73,-192,-86,-73,-162,-170,-63,-60,-94
103,사직동,시/도간전입-전출,91,-16,6,-93,-91,7,1,6,36

In [ ]:
['지역', '구분', 2009 , 2010 : 	2011	2012	2013	2014	2015	2016	2017]

In [ ]:
changes_now_hot.append()

In [516]:
now_hot.to_csv('hots.csv', index=False)